#!/bin/bash
cmake -DPLUGIN_IMAGE=ON  -DPLUGIN_CGALPLUGIN=ON \
	-DPLUGIN_MANUALMAPPING=ON \
	-DPLUGIN_SOFAALLCOMMONCOMPONENTS=ON \
	-DPLUGIN_SOFADISTANCEGRID=ON \
	-DMODULE_SOFASPARSESOLVER=ON \
	-DPLUGIN_SOFAEULERIANFLUID=ON \
	-DPLUGIN_DIFFUSIONSOLVER=ON \
	-DPLUGIN_SOFAPYTHON=ON \
	-DPLUGIN_VOLUMETRICRENDERING=ON \
	-DSOFA_BUILD_METIS=ON \
	-DPLUGIN_STLIB=ON \
	-DPLUGIN_SOFTROBOTS=ON \
	-DPLUGIN_ZYROSCONNECTOR=ON \
	-DSOFA_BUILD_MINIFLOWVR=ON \
	-DPLUGIN_MULTITHREADINBG=ON \
	.. #-DPLUGIN_PSL=ON -DPLUGIN_VolumetricRendering=ON -DPLUGIN_SOFACUDA=ON

echo -e "\nNow making\n\n"

make -j$nproc

echo -e "\n\nNow installing in build folder\n\ns"

make install
