:: Activation script

:: Create compile_commands.json for language server
set CMAKE_EXPORT_COMPILE_COMMANDS=1

:: Activate color output with Ninja
set CMAKE_COLOR_DIAGNOSTICS=1

:: Each environment have its dedicated build dir
set VISP_BUILD_DIR=%CONDA_PREFIX%\visp-build

:: Set default build value only if not previously set
if not defined SOFA_CMAKE_PREFIX_PATH (set SOFA_CMAKE_PREFIX_PATH=%CONDA_PREFIX%)
if not defined SOFA_BUILD_TYPE (set SOFA_BUILD_TYPE=Release)
if not defined SOFA_PLUGIN_SOFAMATRIX (set SOFA_PLUGIN_SOFAMATRIX=OFF)
if not defined SOFA_APPLICATION_SOFAPHYSICSAPI (set SOFA_APPLICATION_SOFAPHYSICSAPI=OFF)
if not defined SOFA_APPLICATION_SOFAINFO (set SOFA_APPLICATION_SOFAINFO=OFF)
if not defined SOFA_BUILD_SCENECREATOR (set SOFA_BUILD_SCENECREATOR=OFF)
if not defined SOFA_BUILD_TUTORIALS (set SOFA_BUILD_TUTORIALS=OFF)
if not defined SOFA_DUMP_VISITOR_INFO (set SOFA_DUMP_VISITOR_INFO=OFF)
if not defined SOFA_PLUGIN_SOFA_GUI_QT (set SOFA_PLUGIN_SOFA_GUI_QT=OFF)
if not defined SOFA_NO_OPENGL (set SOFA_NO_OPENGL=ON)
if not defined SOFA_WITH_OPENGL (set SOFA_WITH_OPENGL=OFF)
if not defined SOFA_WITH_DEVTOOLS (set SOFA_WITH_DEVTOOLS=OFF)
if not defined SOFA_BUILD_RELEASE_PACKAGE (set SOFA_BUILD_RELEASE_PACKAGE=OFF)
if not defined SOFA_PLUGIN_CIMG (set SOFA_PLUGIN_CIMG=OFF)
if not defined SOFA_PLUGIN_DIFFUSIONSOLVER (set SOFA_PLUGIN_DIFFUSIONSOLVER=OFF)
if not defined SOFA_PLUGIN_GEOMAGIC (set SOFA_PLUGIN_GEOMAGIC=OFF)
if not defined SOFA_PLUGIN_IMAGE (set SOFA_PLUGIN_IMAGE=OFF)
if not defined SOFA_PLUGIN_MULTITHREADING (set SOFA_PLUGIN_MULTITHREADING=OFF)
if not defined SOFA_PLUGIN_CARVING (set SOFA_PLUGIN_CARVING=OFF)
if not defined SOFA_PLUGIN_DISTANCEGRID (set SOFA_PLUGIN_DISTANCEGRID=OFF)
if not defined SOFA_PLUGIN_EULERIANFLUID (set SOFA_PLUGIN_EULERIANFLUID=OFF)
if not defined SOFA_PLUGIN_IMPLICITFIELD (set SOFA_PLUGIN_IMPLICITFIELD=OFF)
if not defined SOFA_PLUGIN_COLLISIONOBBCAPSULE (set SOFA_PLUGIN_COLLISIONOBBCAPSULE=OFF)
if not defined SOFA_PLUGIN_VOLUMETRICRENDERING (set SOFA_PLUGIN_VOLUMETRICRENDERING=OFF)