#! /bin/bash
# Activation script

# Create compile_commands.json for language server
export CMAKE_EXPORT_COMPILE_COMMANDS=1

# Activate color output with Ninja
export CMAKE_COLOR_DIAGNOSTICS=1

# Set default build value only if not previously set
export SOFA_CMAKE_PREFIX_PATH=${SOFA_CMAKE_PREFIX_PATH:=$CONDA_PREFIX}
export SOFA_BUILD_TYPE=${SOFA_BUILD_TYPE:=Release}
export SOFA_PLUGIN_SOFAMATRIX=${SOFA_PLUGIN_SOFAMATRIX:=OFF}
export SOFA_APPLICATION_SOFAPHYSICSAPI=${SOFA_APPLICATION_SOFAPHYSICSAPI:=OFF}
export SOFA_APPLICATION_SOFAINFO=${SOFA_APPLICATION_SOFAINFO:=OFF}
export SOFA_BUILD_SCENECREATOR=${SOFA_BUILD_SCENECREATOR:=OFF}
export SOFA_BUILD_TUTORIALS=${SOFA_BUILD_TUTORIALS:=OFF}
export SOFA_DUMP_VISITOR_INFO=${SOFA_DUMP_VISITOR_INFO:=OFF}
export SOFA_PLUGIN_SOFA_GUI_QT=${SOFA_PLUGIN_SOFA_GUI_QT:=OFF}
export SOFA_NO_OPENGL=${SOFA_NO_OPENGL:=ON}
export SOFA_WITH_OPENGL=${SOFA_WITH_OPENGL:=OFF}
export SOFA_WITH_DEVTOOLS=${SOFA_WITH_DEVTOOLS:=OFF}
export SOFA_BUILD_RELEASE_PACKAGE=${SOFA_BUILD_RELEASE_PACKAGE:=OFF}
export SOFA_PLUGIN_CIMG=${SOFA_PLUGIN_CIMG:=OFF}
export SOFA_PLUGIN_DIFFUSIONSOLVER=${SOFA_PLUGIN_DIFFUSIONSOLVER:=OFF}
export SOFA_PLUGIN_GEOMAGIC=${SOFA_PLUGIN_GEOMAGIC:=OFF}
export SOFA_PLUGIN_IMAGE=${SOFA_PLUGIN_IMAGE:=OFF}
export SOFA_PLUGIN_MULTITHREADING=${SOFA_PLUGIN_MULTITHREADING:=OFF}
export SOFA_PLUGIN_CARVING=${SOFA_PLUGIN_CARVING:=OFF}
export SOFA_PLUGIN_DISTANCEGRID=${SOFA_PLUGIN_DISTANCEGRID:=OFF}
export SOFA_PLUGIN_EULERIANFLUID=${SOFA_PLUGIN_EULERIANFLUID:=OFF}
export SOFA_PLUGIN_IMPLICITFIELD=${SOFA_PLUGIN_IMPLICITFIELD:=OFF}
export SOFA_PLUGIN_COLLISIONOBBCAPSULE=${SOFA_PLUGIN_COLLISIONOBBCAPSULE:=OFF}
export SOFA_PLUGIN_VOLUMETRICRENDERING=${SOFA_PLUGIN_VOLUMETRICRENDERING:=OFF}

