set(SOFABASECOLLISION_SRC src/SofaBaseCollision)
set(SOFAMESHCOLLISION_SRC src/SofaMeshCollision)
set(SOFAGENERALMESHCOLLISION_SRC src/SofaGeneralMeshCollision)
set(SOFAUSERINTERACTION_SRC src/SofaUserInteraction)

list(APPEND HEADER_FILES
    ${SOFABASECOLLISION_SRC}/BruteForceBroadPhase.h
    ${SOFABASECOLLISION_SRC}/BruteForceDetection.h
    ${SOFABASECOLLISION_SRC}/BVHNarrowPhase.h
    ${SOFABASECOLLISION_SRC}/DefaultPipeline.h
    ${SOFABASECOLLISION_SRC}/MirrorIntersector.h
    ${SOFAMESHCOLLISION_SRC}/CollisionPM.h
    ${SOFAMESHCOLLISION_SRC}/EndPoint.h
    ${SOFAGENERALMESHCOLLISION_SRC}/DirectSAP.h
    ${SOFAGENERALMESHCOLLISION_SRC}/DirectSAPNarrowPhase.h
    ${SOFAGENERALMESHCOLLISION_SRC}/DSAPBox.h
    ${SOFAGENERALMESHCOLLISION_SRC}/IncrSAP.h
    ${SOFAGENERALMESHCOLLISION_SRC}/RayTraceNarrowPhase.h
    ${SOFAUSERINTERACTION_SRC}/RayTraceDetection.h
)