/******************************************************************************
*       SOFA, Simulation Open-Framework Architecture, v17.06                  *
*                (c) 2006-2017 INRIA, USTL, UJF, CNRS, MGH                    *
*                                                                             *
* This program is free software; you can redistribute it and/or modify it     *
* under the terms of the GNU Lesser General Public License as published by    *
* the Free Software Foundation; either version 2.1 of the License, or (at     *
* your option) any later version.                                             *
*                                                                             *
* This program is distributed in the hope that it will be useful, but WITHOUT *
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or       *
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License *
* for more details.                                                           *
*                                                                             *
* You should have received a copy of the GNU Lesser General Public License    *
* along with this program. If not, see <http://www.gnu.org/licenses/>.        *
*******************************************************************************
* Authors: The SOFA Team and external contributors (see Authors.txt)          *
*                                                                             *
* Contact information: contact@sofa-framework.org                             *
******************************************************************************/



// File automatically generated by "generateTypedef"


#ifndef SOFA_TYPEDEF
#define SOFA_TYPEDEF


//Compilation WITHOUT double
#ifndef SOFA_DOUBLE
#include <sofa/component/typedef/Sofa_float.h>
#endif

//Compilation WITHOUT float
#ifndef SOFA_FLOAT
#include <sofa/component/typedef/Sofa_double.h>
#endif


#ifndef SOFA_DOUBLE
#ifndef SOFA_FLOAT

#include <sofa/component/typedef/ForceField_combination.h>
#include <sofa/component/typedef/InteractionForceField_combination.h>
#include <sofa/component/typedef/Mapping_combination.h>
#include <sofa/component/typedef/Topology_combination.h>

#endif
#endif
#endif
