/******************************************************************************
*       SOFA, Simulation Open-Framework Architecture, v17.06                  *
*                (c) 2006-2017 INRIA, USTL, UJF, CNRS, MGH                    *
*                                                                             *
* This program is free software; you can redistribute it and/or modify it     *
* under the terms of the GNU Lesser General Public License as published by    *
* the Free Software Foundation; either version 2.1 of the License, or (at     *
* your option) any later version.                                             *
*                                                                             *
* This program is distributed in the hope that it will be useful, but WITHOUT *
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or       *
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License *
* for more details.                                                           *
*                                                                             *
* You should have received a copy of the GNU Lesser General Public License    *
* along with this program. If not, see <http://www.gnu.org/licenses/>.        *
*******************************************************************************
* Authors: The SOFA Team and external contributors (see Authors.txt)          *
*                                                                             *
* Contact information: contact@sofa-framework.org                             *
******************************************************************************/



// File automatically generated by "generateTypedef"


#ifndef SOFA_TYPEDEF_DOUBLE
#define SOFA_TYPEDEF_DOUBLE


#include <sofa/component/typedef/Particles_double.h>
#include <sofa/component/typedef/BehaviorModel_double.h>
#include <sofa/component/typedef/CollisionModel_double.h>
#include <sofa/component/typedef/ConstraintSet_double.h>
#include <sofa/component/typedef/ConstraintSolver_double.h>
#include <sofa/component/typedef/Controller_double.h>
#include <sofa/component/typedef/Engine_double.h>
#include <sofa/component/typedef/ForceField_double.h>
#include <sofa/component/typedef/InteractionForceField_double.h>
#include <sofa/component/typedef/LinearSolver_double.h>
#include <sofa/component/typedef/Mapping_double.h>
#include <sofa/component/typedef/Mass_double.h>
#include <sofa/component/typedef/MechanicalState_double.h>
#include <sofa/component/typedef/ProjectiveConstraintSet_double.h>
#include <sofa/component/typedef/Topology_double.h>
#include <sofa/component/typedef/TopologyObject_double.h>
#include <sofa/component/typedef/VisualModel_double.h>
#include <sofa/component/typedef/_Miscellaneous_double.h>

#endif
