/******************************************************************************
*       SOFA, Simulation Open-Framework Architecture, v17.06                  *
*                (c) 2006-2017 INRIA, USTL, UJF, CNRS, MGH                    *
*                                                                             *
* This program is free software; you can redistribute it and/or modify it     *
* under the terms of the GNU Lesser General Public License as published by    *
* the Free Software Foundation; either version 2.1 of the License, or (at     *
* your option) any later version.                                             *
*                                                                             *
* This program is distributed in the hope that it will be useful, but WITHOUT *
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or       *
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License *
* for more details.                                                           *
*                                                                             *
* You should have received a copy of the GNU Lesser General Public License    *
* along with this program. If not, see <http://www.gnu.org/licenses/>.        *
*******************************************************************************
* Authors: The SOFA Team and external contributors (see Authors.txt)          *
*                                                                             *
* Contact information: contact@sofa-framework.org                             *
******************************************************************************/



// File automatically generated by "generateTypedef"


#ifndef SOFA_TYPEDEF_VisualModel_float_H
#define SOFA_TYPEDEF_VisualModel_float_H

//Default files containing the declaration of the vector type
#include <sofa/defaulttype/VecTypes.h>
#include <sofa/defaulttype/RigidTypes.h>
#include <sofa/defaulttype/Mat.h>



#ifndef SOFA_NO_OPENGL
#include <SofaOpenglVisual/OglModel.h>
#include <SofaOpenglVisual/OglShaderVisualModel.h>
#endif

#include <SofaBaseVisual/VisualModelImpl.h>


#ifndef SOFA_NO_OPENGL
//---------------------------------------------------------------------------------------------
//Typedef for OglModel
typedef sofa::component::visualmodel::OglModel OglModelExt3f;



//---------------------------------------------------------------------------------------------
//Typedef for OglShaderVisualModel
typedef sofa::component::visualmodel::OglShaderVisualModel OglShaderVisualModelExt3f;



//---------------------------------------------------------------------------------------------
//Typedef for VisualModelImpl
typedef sofa::component::visualmodel::VisualModelImpl VisualModelImplExt3f;





#ifdef SOFA_FLOAT
#ifndef SOFA_NO_OPENGL
typedef OglModelExt3f OglModelExt3;
typedef OglShaderVisualModelExt3f OglShaderVisualModelExt3;
#endif
typedef VisualModelImplExt3f VisualModelImplExt3;
#endif

#endif

#endif
