set(PYTHON_FILES
        python/Compliant/__init__.py
        python/Compliant/Control.py
        python/Compliant/Quaternion.py
        python/Compliant/Rigid.py
        python/Compliant/Script.py
        python/Compliant/Tools.py
        python/Compliant/Vec.py
        python/Compliant/StructuralAPI.py
        python/Compliant/sml.py
        )
