message("CPACK_GENERATOR= ${CPACK_GENERATOR}")

execute_process(COMMAND bash "${CMAKE_CURRENT_LIST_DIR}/generate-stubfiles.sh" "${CMAKE_BINARY_DIR}" "${CPACK_TEMPORARY_INSTALL_DIRECTORY}" "${CMAKE_SYSTEM_NAME}:${CPACK_GENERATOR}")
