#ifndef SOFA_DEFAULTTYPE_H
#define SOFA_DEFAULTTYPE_H

#include <sofa/helper/system/config.h>

#ifdef SOFA_BUILD_DEFAULTTYPE
#	define SOFA_DEFAULTTYPE_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#	define SOFA_DEFAULTTYPE_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif

#endif
