
set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} -arch ${SOFACUDA_ARCH} -Xcompiler")
if(NOT WIN32)
    set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} -fPIC")
endif()
set(CUDA_NVCC_FLAGS_DEBUG "-g")
set(CUDA_NVCC_FLAGS_RELEASE "-DNDEBUG")
