set(SOFABASECOLLISION_SRC src/SofaBaseCollision)
set(SOFAMESHCOLLISION_SRC src/SofaMeshCollision)
set(SOFAUSERINTERACTION_SRC src/SofaUserInteraction)
set(SOFAGENERALMESHCOLLISION_SRC src/SofaGeneralMeshCollision)
set(SOFAMISCCOLLISION_SRC src/SofaMiscCollision)

list(APPEND HEADER_FILES
    ${SOFABASECOLLISION_SRC}/fwd.h
    ${SOFABASECOLLISION_SRC}/CubeModel.h
    ${SOFABASECOLLISION_SRC}/CylinderModel.h
    ${SOFABASECOLLISION_SRC}/CylinderModel.inl
    ${SOFABASECOLLISION_SRC}/SphereModel.h
    ${SOFABASECOLLISION_SRC}/SphereModel.inl  
    ${SOFAMESHCOLLISION_SRC}/LineModel.h
    ${SOFAMESHCOLLISION_SRC}/LineModel.inl    
    ${SOFAMESHCOLLISION_SRC}/PointModel.h
    ${SOFAMESHCOLLISION_SRC}/PointModel.inl
    ${SOFAMESHCOLLISION_SRC}/TriangleModel.h
    ${SOFAMESHCOLLISION_SRC}/TriangleModel.inl
    ${SOFAUSERINTERACTION_SRC}/Ray.h
    ${SOFAUSERINTERACTION_SRC}/RayModel.h
    ${SOFAGENERALMESHCOLLISION_SRC}/TriangleOctree.h
    ${SOFAGENERALMESHCOLLISION_SRC}/TriangleOctreeModel.h
    ${SOFAMISCCOLLISION_SRC}/TetrahedronModel.h
    ${SOFAMISCCOLLISION_SRC}/TriangleModelInRegularGrid.h
)
