##########################################
# Sofa :: Simulation CPack configuration #
##########################################

if(UNIX)
    set(CPACK_GENERATOR "DEB")
    set(CPACK_DEBIAN_PACKAGE_DEPENDS "sofaframework-dev")
elseif(WIN32)
    set(CPACK_GENERATOR "NSIS")
elseif(APPLE)
    set(CPACK_GENERATOR "ZIP")
endif()

set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/../../../readme.txt")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/../../copyright.txt")
set(CPACK_PACKAGE_VERSION_MAJOR "${SOFASIMULATION_MAJOR_VERSION}")
set(CPACK_PACKAGE_VERSION_MINOR "${SOFASIMULATION_MINOR_VERSION}")
set(CPACK_PACKAGE_VERSION_PATCH "${SOFASIMULATION_BUILD_VERSION}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "SofaSimulation libraries")
set(CPACK_PACKAGE_MAINTAINER "INRIA") #required
set(CPACK_PACKAGE_CONTACT "sofa-users@lists.gforge.inria.fr")
 
set(CPACK_COMPONENT_SOFASIMULATION_LIBRARIES_DISPLAY_NAME "libs" )
set(CPACK_COMPONENT_SOFASIMULATION_SOURCES_DISPLAY_NAME "c++ sources" )
set(CPACK_COMPONENT_SOFASIMULATION_LIBRARIES_GROUP "SofaSimulation" )
set(CPACK_COMPONENT_SOFASIMULATION_SOURCES_GROUP   "SofaSimulation" )
set(CPACK_COMPONENT_GROUP_SOFASIMULATION_DESCRIPTION "The SofaSimulation package") 

