cmake_minimum_required(VERSION 3.22)
project(Sofa.Component.IntegrationScheme.Backward LANGUAGES CXX)

set(SOFACOMPONENTINTEGRATIONSCHEMEBACKWARD_SOURCE_DIR "src/sofa/component/integrationscheme/backward")

set(HEADER_FILES
    ${SOFACOMPONENTINTEGRATIONSCHEMEBACKWARD_SOURCE_DIR}/config.h.in
    ${SOFACOMPONENTINTEGRATIONSCHEMEBACKWARD_SOURCE_DIR}/init.h
    ${SOFACOMPONENTINTEGRATIONSCHEMEBACKWARD_SOURCE_DIR}/EulerImplicitIntegrationScheme.h
    ${SOFACOMPONENTINTEGRATIONSCHEMEBACKWARD_SOURCE_DIR}/NewmarkIntegrationScheme.h
    ${SOFACOMPONENTINTEGRATIONSCHEMEBACKWARD_SOURCE_DIR}/LinearMultistepIntegrationScheme.h
    ${SOFACOMPONENTINTEGRATIONSCHEMEBACKWARD_SOURCE_DIR}/BDFIntegrationScheme.h
    ${SOFACOMPONENTINTEGRATIONSCHEMEBACKWARD_SOURCE_DIR}/StaticEquilibriumIntegrationScheme.h
)

set(SOURCE_FILES
    ${SOFACOMPONENTINTEGRATIONSCHEMEBACKWARD_SOURCE_DIR}/init.cpp
    ${SOFACOMPONENTINTEGRATIONSCHEMEBACKWARD_SOURCE_DIR}/EulerImplicitIntegrationScheme.cpp
    ${SOFACOMPONENTINTEGRATIONSCHEMEBACKWARD_SOURCE_DIR}/NewmarkIntegrationScheme.cpp
    ${SOFACOMPONENTINTEGRATIONSCHEMEBACKWARD_SOURCE_DIR}/LinearMultistepIntegrationScheme.cpp
    ${SOFACOMPONENTINTEGRATIONSCHEMEBACKWARD_SOURCE_DIR}/BDFIntegrationScheme.cpp
    ${SOFACOMPONENTINTEGRATIONSCHEMEBACKWARD_SOURCE_DIR}/StaticEquilibriumIntegrationScheme.cpp
)

sofa_find_package(Sofa.Simulation.Core REQUIRED)

add_library(${PROJECT_NAME} SHARED ${HEADER_FILES} ${SOURCE_FILES})
target_link_libraries(${PROJECT_NAME} PUBLIC Sofa.Simulation.Core)
target_include_directories(${PROJECT_NAME} PUBLIC
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/compat>
    $<INSTALL_INTERFACE:include/${PROJECT_NAME}_compat>
)

sofa_create_package_with_targets(
    PACKAGE_NAME ${PROJECT_NAME}
    PACKAGE_VERSION ${Sofa_VERSION}
    TARGETS ${PROJECT_NAME} AUTO_SET_TARGET_PROPERTIES
    INCLUDE_SOURCE_DIR "src"
    INCLUDE_INSTALL_DIR "${PROJECT_NAME}"
)

cmake_dependent_option(SOFA_COMPONENT_INTEGRATIONSCHEME_BACKWARD_BUILD_TESTS "Compile the automatic tests" ON "SOFA_BUILD_TESTS OR NOT DEFINED SOFA_BUILD_TESTS" OFF)
if(SOFA_COMPONENT_INTEGRATIONSCHEME_BACKWARD_BUILD_TESTS)
    add_subdirectory(tests)
endif()

