#! /bin/bash

date=`date '+%Y-%m-%dT%H:%M:%S'`
testName="headlessRecorder_test"
arg0=$0
arg1=$1
output="${arg1#*:}"
reportBegin="<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
reportHeader=""
reportBody=""
reportFoot="</testsuite>
            </testsuites>"

tests=0
failures=0
errors=0
timer=0
echo "$arg0"
echo "OK"

# first test, check result file size
run_test()
{
    local timeSecond=0
    local timeMilliSecond=0
    local minimalSize=30000 # should be greater than 27kb
    local currentTestName="size_check"

    echo "[ RUN      ] $testName.$currentTestName"
    STARTTIME=$(date +%s%N | cut -b1-13)
    ${arg0/$testName/runSofa} -g hRecorder --video --fps=60 -a --filename tmp
    ENDTIME=$(date +%s%N | cut -b1-13)
    local fileSize=$(stat -c%s "tmp.avi")
    rm tmp.avi
    tests=$((tests + 1))

    if [[ "$fileSize" -ge "$minimalSize" ]]; then
        echo "[       OK ] $testName.$currentTestName ( ms)"
    else
        echo "[ERROR] $testName.$currentTestName ($(($ENDTIME - $STARTTIME)) ms) size too small: $fileSize"
        errors=$((errors + 1))
    fi
    timer=$((timer + $ENDTIME - $STARTTIME))

}

run_test
reportHeader="
        <testsuites tests=\"1\" failures=\""$failures"\" disabled="0" errors=\""$errors"\" timestamp=\"$date\" time=\""$(($timer/1000))"."$(($timer%1000))"\" name=\"AllTests\">

    <testsuite name=\""$testName"\" tests=\""$tests"\" failures=\""$failures"\" disabled=\"0\" errors=\""$errors"\" time=\""$(($timer/1000))"."$(($timer%1000))"\">"

echo $reportBegin $reportHeader $reportBody $reportFoot > $output
