#ifndef SOFACOMBINATORIALMAPS_CONFIG_H
#define SOFACOMBINATORIALMAPS_CONFIG_H

#include <sofa/config/sharedlibrary_defines.h>

#ifdef SOFA_BUILD_SOFACOMBINATORIALMAPS
#  define SOFA_TARGET SofaCombinatorialMaps
#  define SOFA_COMBINATORIALMAPS_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define SOFA_COMBINATORIALMAPS_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif

#endif
