#ifndef SOFA_COMPONENT_INITVOXELLOADER_H
#define SOFA_COMPONENT_INITVOXELLOADER_H


#include <sofa/helper/system/config.h>

#ifdef SOFA_BUILD_VOXELIZER
#	define SOFA_VOXELIZER_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#	define SOFA_VOXELIZER_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif


#endif // SOFA_COMPONENT_INITVOXELLOADER_H
