#ifndef SOFA_PLUGIN_PERSISTENTCONTACT_H
#define SOFA_PLUGIN_PERSISTENTCONTACT_H

#ifndef WIN32
#define SOFA_EXPORT_DYNAMIC_LIBRARY
#define SOFA_IMPORT_DYNAMIC_LIBRARY
#define SOFA_PERSISTENTCONTACT_API
#else
#ifdef SOFA_BUILD_PERSISTENTCONTACT
#define SOFA_EXPORT_DYNAMIC_LIBRARY __declspec( dllexport )
#define SOFA_PERSISTENTCONTACT_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#define SOFA_IMPORT_DYNAMIC_LIBRARY __declspec( dllimport )
#define SOFA_PERSISTENTCONTACT_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif
#endif

SOFA_PERSISTENTCONTACT_API void initPersistentContact();

#endif // SOFA_PLUGIN_PERSISTENTCONTACT_H
