s:#include *[<"]sofa/component/animationloop/MultiTagAnimationLoop.h[>"]:#include <SofaBaseAnimationLoop/MultiTagAnimationLoop.h>:
s:#include *[<"]sofa/component/animationloop/MultiStepAnimationLoop.h[>"]:#include <SofaBaseAnimationLoop/MultiStepAnimationLoop.h>:
s:#include *[<"]sofa/component/collision/ContactListener.h[>"]:#include <SofaBaseCollision/ContactListener.h>:
s:#include *[<"]sofa/component/collision/BaseIntTool.h[>"]:#include <SofaBaseCollision/BaseIntTool.h>:
s:#include *[<"]sofa/component/collision/Intersector.h[>"]:#include <SofaBaseCollision/Intersector.h>:
s:#include *[<"]sofa/component/collision/IntrSphereOBB.inl[>"]:#include <SofaBaseCollision/IntrSphereOBB.inl>:
s:#include *[<"]sofa/component/collision/IntrCapsuleOBB.inl[>"]:#include <SofaBaseCollision/IntrCapsuleOBB.inl>:
s:#include *[<"]sofa/component/collision/IntrCapsuleOBB.h[>"]:#include <SofaBaseCollision/IntrCapsuleOBB.h>:
s:#include *[<"]sofa/component/collision/IntrSphereOBB.h[>"]:#include <SofaBaseCollision/IntrSphereOBB.h>:
s:#include *[<"]sofa/component/collision/IntrUtility3.inl[>"]:#include <SofaBaseCollision/IntrUtility3.inl>:
s:#include *[<"]sofa/component/collision/IntrUtility3.h[>"]:#include <SofaBaseCollision/IntrUtility3.h>:
s:#include *[<"]sofa/component/collision/IntrOBBOBB.inl[>"]:#include <SofaBaseCollision/IntrOBBOBB.inl>:
s:#include *[<"]sofa/component/collision/IntrOBBOBB.h[>"]:#include <SofaBaseCollision/IntrOBBOBB.h>:
s:#include *[<"]sofa/component/collision/OBBIntTool.h[>"]:#include <SofaBaseCollision/OBBIntTool.h>:
s:#include *[<"]sofa/component/collision/RigidCapsuleModel.inl[>"]:#include <SofaBaseCollision/RigidCapsuleModel.inl>:
s:#include *[<"]sofa/component/collision/RigidCapsuleModel.h[>"]:#include <SofaBaseCollision/RigidCapsuleModel.h>:
s:#include *[<"]sofa/component/collision/OBBModel.h[>"]:#include <SofaBaseCollision/OBBModel.h>:
s:#include *[<"]sofa/component/collision/OBBModel.inl[>"]:#include <SofaBaseCollision/OBBModel.inl>:
s:#include *[<"]sofa/component/collision/CapsuleIntTool.inl[>"]:#include <SofaBaseCollision/CapsuleIntTool.inl>:
s:#include *[<"]sofa/component/collision/CapsuleIntTool.h[>"]:#include <SofaBaseCollision/CapsuleIntTool.h>:
s:#include *[<"]sofa/component/collision/BaseProximityIntersection.h[>"]:#include <SofaBaseCollision/BaseProximityIntersection.h>:
s:#include *[<"]sofa/component/collision/CapsuleModel.inl[>"]:#include <SofaBaseCollision/CapsuleModel.inl>:
s:#include *[<"]sofa/component/collision/CapsuleModel.h[>"]:#include <SofaBaseCollision/CapsuleModel.h>:
s:#include *[<"]sofa/component/collision/NewProximityIntersection.inl[>"]:#include <SofaBaseCollision/NewProximityIntersection.inl>:
s:#include *[<"]sofa/component/collision/NewProximityIntersection.h[>"]:#include <SofaBaseCollision/NewProximityIntersection.h>:
s:#include *[<"]sofa/component/collision/MinProximityIntersection.h[>"]:#include <SofaBaseCollision/MinProximityIntersection.h>:
s:#include *[<"]sofa/component/collision/DefaultContactManager.h[>"]:#include <SofaBaseCollision/DefaultContactManager.h>:
s:#include *[<"]sofa/component/collision/BruteForceDetection.h[>"]:#include <SofaBaseCollision/BruteForceDetection.h>:
s:#include *[<"]sofa/component/collision/DiscreteIntersection.h[>"]:#include <SofaBaseCollision/DiscreteIntersection.h>:
s:#include *[<"]sofa/component/collision/CubeModel.h[>"]:#include <SofaBaseCollision/CubeModel.h>:
s:#include *[<"]sofa/component/collision/Cube.h[>"]:#include <SofaBaseCollision/Cube.h>:
s:#include *[<"]sofa/component/collision/SphereModel.inl[>"]:#include <SofaBaseCollision/SphereModel.inl>:
s:#include *[<"]sofa/component/collision/SphereModel.h[>"]:#include <SofaBaseCollision/SphereModel.h>:
s:#include *[<"]sofa/component/collision/Sphere.h[>"]:#include <SofaBaseCollision/Sphere.h>:
s:#include *[<"]sofa/component/collision/DefaultPipeline.h[>"]:#include <SofaBaseCollision/DefaultPipeline.h>:
s:#include *[<"]sofa/component/collision/BaseContactMapper.h[>"]:#include <SofaBaseCollision/BaseContactMapper.h>:
s:#include *[<"]sofa/component/linearsolver/MinResLinearSolver.inl[>"]:#include <SofaBaseLinearSolver/MinResLinearSolver.inl>:
s:#include *[<"]sofa/component/linearsolver/MinResLinearSolver.h[>"]:#include <SofaBaseLinearSolver/MinResLinearSolver.h>:
s:#include *[<"]sofa/component/linearsolver/BlocMatrixWriter.h[>"]:#include <SofaBaseLinearSolver/BlocMatrixWriter.h>:
s:#include *[<"]sofa/component/linearsolver/matrix_bloc_traits.h[>"]:#include <SofaBaseLinearSolver/matrix_bloc_traits.h>:
s:#include *[<"]sofa/component/linearsolver/MatrixExpr.h[>"]:#include <SofaBaseLinearSolver/MatrixExpr.h>:
s:#include *[<"]sofa/component/linearsolver/MatrixLinearSolver.inl[>"]:#include <SofaBaseLinearSolver/MatrixLinearSolver.inl>:
s:#include *[<"]sofa/component/linearsolver/MatrixLinearSolver.h[>"]:#include <SofaBaseLinearSolver/MatrixLinearSolver.h>:
s:#include *[<"]sofa/component/linearsolver/DefaultMultiMatrixAccessor.h[>"]:#include <SofaBaseLinearSolver/DefaultMultiMatrixAccessor.h>:
s:#include *[<"]sofa/component/linearsolver/GraphScatteredTypes.h[>"]:#include <SofaBaseLinearSolver/GraphScatteredTypes.h>:
s:#include *[<"]sofa/component/linearsolver/CompressedRowSparseMatrix.inl[>"]:#include <SofaBaseLinearSolver/CompressedRowSparseMatrix.inl>:
s:#include *[<"]sofa/component/linearsolver/CompressedRowSparseMatrix.h[>"]:#include <SofaBaseLinearSolver/CompressedRowSparseMatrix.h>:
s:#include *[<"]sofa/component/linearsolver/SparseMatrix.h[>"]:#include <SofaBaseLinearSolver/SparseMatrix.h>:
s:#include *[<"]sofa/component/linearsolver/SingleMatrixAccessor.h[>"]:#include <SofaBaseLinearSolver/SingleMatrixAccessor.h>:
s:#include *[<"]sofa/component/linearsolver/DiagonalMatrix.h[>"]:#include <SofaBaseLinearSolver/DiagonalMatrix.h>:
s:#include *[<"]sofa/component/linearsolver/FullMatrix.h[>"]:#include <SofaBaseLinearSolver/FullMatrix.h>:
s:#include *[<"]sofa/component/linearsolver/FullVector.h[>"]:#include <SofaBaseLinearSolver/FullVector.h>:
s:#include *[<"]sofa/component/linearsolver/BTDLinearSolver.inl[>"]:#include <SofaBaseLinearSolver/BTDLinearSolver.inl>:
s:#include *[<"]sofa/component/linearsolver/BTDLinearSolver.h[>"]:#include <SofaBaseLinearSolver/BTDLinearSolver.h>:
s:#include *[<"]sofa/component/linearsolver/CholeskySolver.inl[>"]:#include <SofaBaseLinearSolver/CholeskySolver.inl>:
s:#include *[<"]sofa/component/linearsolver/CholeskySolver.h[>"]:#include <SofaBaseLinearSolver/CholeskySolver.h>:
s:#include *[<"]sofa/component/linearsolver/CGLinearSolver.inl[>"]:#include <SofaBaseLinearSolver/CGLinearSolver.inl>:
s:#include *[<"]sofa/component/linearsolver/CGLinearSolver.h[>"]:#include <SofaBaseLinearSolver/CGLinearSolver.h>:
s:#include *[<"]sofa/component/container/MechanicalObjectTasks.inl[>"]:#include <SofaBaseMechanics/MechanicalObjectTasks.inl>:
s:#include *[<"]sofa/component/mapping/SubsetMapping.inl[>"]:#include <SofaBaseMechanics/SubsetMapping.inl>:
s:#include *[<"]sofa/component/mapping/SubsetMapping.h[>"]:#include <SofaBaseMechanics/SubsetMapping.h>:
s:#include *[<"]sofa/component/mapping/IdentityMapping.inl[>"]:#include <SofaBaseMechanics/IdentityMapping.inl>:
s:#include *[<"]sofa/component/mapping/IdentityMapping.h[>"]:#include <SofaBaseMechanics/IdentityMapping.h>:
s:#include *[<"]sofa/component/mapping/BarycentricMapping.inl[>"]:#include <SofaBaseMechanics/BarycentricMapping.inl>:
s:#include *[<"]sofa/component/mapping/BarycentricMapping.h[>"]:#include <SofaBaseMechanics/BarycentricMapping.h>:
s:#include *[<"]sofa/component/mass/UniformMass.inl[>"]:#include <SofaBaseMechanics/UniformMass.inl>:
s:#include *[<"]sofa/component/mass/UniformMass.h[>"]:#include <SofaBaseMechanics/UniformMass.h>:
s:#include *[<"]sofa/component/mass/DiagonalMass.inl[>"]:#include <SofaBaseMechanics/DiagonalMass.inl>:
s:#include *[<"]sofa/component/mass/DiagonalMass.h[>"]:#include <SofaBaseMechanics/DiagonalMass.h>:
s:#include *[<"]sofa/component/mass/AddMToMatrixFunctor.h[>"]:#include <SofaBaseMechanics/AddMToMatrixFunctor.h>:
s:#include *[<"]sofa/component/container/MechanicalObject.inl[>"]:#include <SofaBaseMechanics/MechanicalObject.inl>:
s:#include *[<"]sofa/component/container/MechanicalObject.h[>"]:#include <SofaBaseMechanics/MechanicalObject.h>:
s:#include *[<"]sofa/component/container/MappedObject.inl[>"]:#include <SofaBaseMechanics/MappedObject.inl>:
s:#include *[<"]sofa/component/container/MappedObject.h[>"]:#include <SofaBaseMechanics/MappedObject.h>:
s:#include *[<"]sofa/component/topology/TopologyEngine.inl[>"]:#include <SofaBaseTopology/TopologyEngine.inl>:
s:#include *[<"]sofa/component/topology/TopologyEngine.h[>"]:#include <SofaBaseTopology/TopologyEngine.h>:
s:#include *[<"]sofa/component/topology/TopologySubsetDataHandler.inl[>"]:#include <SofaBaseTopology/TopologySubsetDataHandler.inl>:
s:#include *[<"]sofa/component/topology/TopologySubsetDataHandler.h[>"]:#include <SofaBaseTopology/TopologySubsetDataHandler.h>:
s:#include *[<"]sofa/component/topology/TopologySubsetData.inl[>"]:#include <SofaBaseTopology/TopologySubsetData.inl>:
s:#include *[<"]sofa/component/topology/TopologySubsetData.h[>"]:#include <SofaBaseTopology/TopologySubsetData.h>:
s:#include *[<"]sofa/component/topology/TopologySparseData.inl[>"]:#include <SofaBaseTopology/TopologySparseData.inl>:
s:#include *[<"]sofa/component/topology/TopologySparseData.h[>"]:#include <SofaBaseTopology/TopologySparseData.h>:
s:#include *[<"]sofa/component/topology/TopologySparseDataHandler.inl[>"]:#include <SofaBaseTopology/TopologySparseDataHandler.inl>:
s:#include *[<"]sofa/component/topology/TopologySparseDataHandler.h[>"]:#include <SofaBaseTopology/TopologySparseDataHandler.h>:
s:#include *[<"]sofa/component/topology/TopologyDataHandler.inl[>"]:#include <SofaBaseTopology/TopologyDataHandler.inl>:
s:#include *[<"]sofa/component/topology/TopologyDataHandler.h[>"]:#include <SofaBaseTopology/TopologyDataHandler.h>:
s:#include *[<"]sofa/component/topology/TopologyData.inl[>"]:#include <SofaBaseTopology/TopologyData.inl>:
s:#include *[<"]sofa/component/topology/TopologyData.h[>"]:#include <SofaBaseTopology/TopologyData.h>:
s:#include *[<"]sofa/component/topology/TriangleSetTopologyModifier.h[>"]:#include <SofaBaseTopology/TriangleSetTopologyModifier.h>:
s:#include *[<"]sofa/component/topology/TriangleSetTopologyContainer.h[>"]:#include <SofaBaseTopology/TriangleSetTopologyContainer.h>:
s:#include *[<"]sofa/component/topology/TriangleSetTopologyAlgorithms.inl[>"]:#include <SofaBaseTopology/TriangleSetTopologyAlgorithms.inl>:
s:#include *[<"]sofa/component/topology/TriangleSetTopologyAlgorithms.h[>"]:#include <SofaBaseTopology/TriangleSetTopologyAlgorithms.h>:
s:#include *[<"]sofa/component/topology/TriangleSetGeometryAlgorithms.inl[>"]:#include <SofaBaseTopology/TriangleSetGeometryAlgorithms.inl>:
s:#include *[<"]sofa/component/topology/TriangleSetGeometryAlgorithms.h[>"]:#include <SofaBaseTopology/TriangleSetGeometryAlgorithms.h>:
s:#include *[<"]sofa/component/topology/TetrahedronSetTopologyModifier.h[>"]:#include <SofaBaseTopology/TetrahedronSetTopologyModifier.h>:
s:#include *[<"]sofa/component/topology/BezierTetrahedronSetTopologyContainer.h[>"]:#include <SofaBaseTopology/BezierTetrahedronSetTopologyContainer.h>:
s:#include *[<"]sofa/component/topology/TetrahedronSetTopologyContainer.h[>"]:#include <SofaBaseTopology/TetrahedronSetTopologyContainer.h>:
s:#include *[<"]sofa/component/topology/TetrahedronSetTopologyAlgorithms.inl[>"]:#include <SofaBaseTopology/TetrahedronSetTopologyAlgorithms.inl>:
s:#include *[<"]sofa/component/topology/TetrahedronSetTopologyAlgorithms.h[>"]:#include <SofaBaseTopology/TetrahedronSetTopologyAlgorithms.h>:
s:#include *[<"]sofa/component/topology/BezierTetrahedronSetGeometryAlgorithms.inl[>"]:#include <SofaBaseTopology/BezierTetrahedronSetGeometryAlgorithms.inl>:
s:#include *[<"]sofa/component/topology/BezierTetrahedronSetGeometryAlgorithms.h[>"]:#include <SofaBaseTopology/BezierTetrahedronSetGeometryAlgorithms.h>:
s:#include *[<"]sofa/component/topology/TetrahedronSetGeometryAlgorithms.inl[>"]:#include <SofaBaseTopology/TetrahedronSetGeometryAlgorithms.inl>:
s:#include *[<"]sofa/component/topology/TetrahedronSetGeometryAlgorithms.h[>"]:#include <SofaBaseTopology/TetrahedronSetGeometryAlgorithms.h>:
s:#include *[<"]sofa/component/topology/SparseGridTopology.h[>"]:#include <SofaBaseTopology/SparseGridTopology.h>:
s:#include *[<"]sofa/component/topology/RegularGridTopology.h[>"]:#include <SofaBaseTopology/RegularGridTopology.h>:
s:#include *[<"]sofa/component/topology/QuadSetTopologyModifier.h[>"]:#include <SofaBaseTopology/QuadSetTopologyModifier.h>:
s:#include *[<"]sofa/component/topology/QuadSetTopologyContainer.h[>"]:#include <SofaBaseTopology/QuadSetTopologyContainer.h>:
s:#include *[<"]sofa/component/topology/QuadSetTopologyAlgorithms.inl[>"]:#include <SofaBaseTopology/QuadSetTopologyAlgorithms.inl>:
s:#include *[<"]sofa/component/topology/QuadSetTopologyAlgorithms.h[>"]:#include <SofaBaseTopology/QuadSetTopologyAlgorithms.h>:
s:#include *[<"]sofa/component/topology/QuadSetGeometryAlgorithms.inl[>"]:#include <SofaBaseTopology/QuadSetGeometryAlgorithms.inl>:
s:#include *[<"]sofa/component/topology/QuadSetGeometryAlgorithms.h[>"]:#include <SofaBaseTopology/QuadSetGeometryAlgorithms.h>:
s:#include *[<"]sofa/component/topology/PointSetTopologyModifier.h[>"]:#include <SofaBaseTopology/PointSetTopologyModifier.h>:
s:#include *[<"]sofa/component/topology/PointSetTopologyContainer.h[>"]:#include <SofaBaseTopology/PointSetTopologyContainer.h>:
s:#include *[<"]sofa/component/topology/PointSetTopologyAlgorithms.inl[>"]:#include <SofaBaseTopology/PointSetTopologyAlgorithms.inl>:
s:#include *[<"]sofa/component/topology/PointSetTopologyAlgorithms.h[>"]:#include <SofaBaseTopology/PointSetTopologyAlgorithms.h>:
s:#include *[<"]sofa/component/topology/PointSetGeometryAlgorithms.inl[>"]:#include <SofaBaseTopology/PointSetGeometryAlgorithms.inl>:
s:#include *[<"]sofa/component/topology/PointSetGeometryAlgorithms.h[>"]:#include <SofaBaseTopology/PointSetGeometryAlgorithms.h>:
s:#include *[<"]sofa/component/topology/MeshTopology.h[>"]:#include <SofaBaseTopology/MeshTopology.h>:
s:#include *[<"]sofa/component/topology/NumericalIntegrationDescriptor.inl[>"]:#include <SofaBaseTopology/NumericalIntegrationDescriptor.inl>:
s:#include *[<"]sofa/component/topology/NumericalIntegrationDescriptor.h[>"]:#include <SofaBaseTopology/NumericalIntegrationDescriptor.h>:
s:#include *[<"]sofa/component/topology/HexahedronSetTopologyModifier.h[>"]:#include <SofaBaseTopology/HexahedronSetTopologyModifier.h>:
s:#include *[<"]sofa/component/topology/HexahedronSetTopologyContainer.h[>"]:#include <SofaBaseTopology/HexahedronSetTopologyContainer.h>:
s:#include *[<"]sofa/component/topology/HexahedronSetTopologyAlgorithms.inl[>"]:#include <SofaBaseTopology/HexahedronSetTopologyAlgorithms.inl>:
s:#include *[<"]sofa/component/topology/HexahedronSetTopologyAlgorithms.h[>"]:#include <SofaBaseTopology/HexahedronSetTopologyAlgorithms.h>:
s:#include *[<"]sofa/component/topology/HexahedronSetGeometryAlgorithms.inl[>"]:#include <SofaBaseTopology/HexahedronSetGeometryAlgorithms.inl>:
s:#include *[<"]sofa/component/topology/HexahedronSetGeometryAlgorithms.h[>"]:#include <SofaBaseTopology/HexahedronSetGeometryAlgorithms.h>:
s:#include *[<"]sofa/component/topology/GridTopology.h[>"]:#include <SofaBaseTopology/GridTopology.h>:
s:#include *[<"]sofa/component/topology/EdgeSetTopologyModifier.h[>"]:#include <SofaBaseTopology/EdgeSetTopologyModifier.h>:
s:#include *[<"]sofa/component/topology/EdgeSetTopologyContainer.h[>"]:#include <SofaBaseTopology/EdgeSetTopologyContainer.h>:
s:#include *[<"]sofa/component/topology/EdgeSetTopologyAlgorithms.inl[>"]:#include <SofaBaseTopology/EdgeSetTopologyAlgorithms.inl>:
s:#include *[<"]sofa/component/topology/EdgeSetTopologyAlgorithms.h[>"]:#include <SofaBaseTopology/EdgeSetTopologyAlgorithms.h>:
s:#include *[<"]sofa/component/topology/EdgeSetGeometryAlgorithms.inl[>"]:#include <SofaBaseTopology/EdgeSetGeometryAlgorithms.inl>:
s:#include *[<"]sofa/component/topology/EdgeSetGeometryAlgorithms.h[>"]:#include <SofaBaseTopology/EdgeSetGeometryAlgorithms.h>:
s:#include *[<"]sofa/component/topology/SphereQuadTopology.h[>"]:#include <SofaBaseTopology/SphereQuadTopology.h>:
s:#include *[<"]sofa/component/topology/CylinderGridTopology.h[>"]:#include <SofaBaseTopology/CylinderGridTopology.h>:
s:#include *[<"]sofa/component/topology/CubeTopology.h[>"]:#include <SofaBaseTopology/CubeTopology.h>:
s:#include *[<"]sofa/component/topology/CommonAlgorithms.h[>"]:#include <SofaBaseTopology/CommonAlgorithms.h>:
s:#include *[<"]sofa/component/visualmodel/VisualTransform.h[>"]:#include <SofaBaseVisual/VisualTransform.h>:
s:#include *[<"]sofa/component/visualmodel/VisualStyle.h[>"]:#include <SofaBaseVisual/VisualStyle.h>:
s:#include *[<"]sofa/component/visualmodel/VisualModelImpl.h[>"]:#include <SofaBaseVisual/VisualModelImpl.h>:
s:#include *[<"]sofa/component/visualmodel/RecordedCamera.h[>"]:#include <SofaBaseVisual/RecordedCamera.h>:
s:#include *[<"]sofa/component/visualmodel/InteractiveCamera.h[>"]:#include <SofaBaseVisual/InteractiveCamera.h>:
s:#include *[<"]sofa/component/visualmodel/BaseCamera.h[>"]:#include <SofaBaseVisual/BaseCamera.h>:
s:#include *[<"]sofa/component/linearsolver/NewMatMatrix.h[>"]:#include <SofaDenseSolver/NewMatMatrix.h>:
s:#include *[<"]sofa/component/linearsolver/NewMatVector.h[>"]:#include <SofaDenseSolver/NewMatVector.h>:
s:#include *[<"]sofa/component/linearsolver/LULinearSolver.h[>"]:#include <SofaDenseSolver/LULinearSolver.h>:
s:#include *[<"]sofa/component/linearsolver/SVDLinearSolver.h[>"]:#include <SofaEigen2Solver/SVDLinearSolver.h>:
s:#include *[<"]sofa/component/linearsolver/EigenVectorWrapper.h[>"]:#include <SofaEigen2Solver/EigenVectorWrapper.h>:
s:#include *[<"]sofa/component/linearsolver/EigenVector.h[>"]:#include <SofaEigen2Solver/EigenVector.h>:
s:#include *[<"]sofa/component/linearsolver/EigenSparseMatrix.h[>"]:#include <SofaEigen2Solver/EigenSparseMatrix.h>:
s:#include *[<"]sofa/component/linearsolver/EigenBaseSparseMatrix_MT.h[>"]:#include <SofaEigen2Solver/EigenBaseSparseMatrix_MT.h>:
s:#include *[<"]sofa/component/linearsolver/EigenBaseSparseMatrix.h[>"]:#include <SofaEigen2Solver/EigenBaseSparseMatrix.h>:
s:#include *[<"]sofa/component/linearsolver/EigenMatrixManipulator.h[>"]:#include <SofaEigen2Solver/EigenMatrixManipulator.h>:
s:#include *[<"]sofa/component/engine/HausdorffDistance.inl[>"]:#include <SofaEngine/HausdorffDistance.inl>:
s:#include *[<"]sofa/component/engine/HausdorffDistance.h[>"]:#include <SofaEngine/HausdorffDistance.h>:
s:#include *[<"]sofa/component/engine/ProximityROI.inl[>"]:#include <SofaEngine/ProximityROI.inl>:
s:#include *[<"]sofa/component/engine/ProximityROI.h[>"]:#include <SofaEngine/ProximityROI.h>:
s:#include *[<"]sofa/component/engine/ShapeMatching.inl[>"]:#include <SofaEngine/ShapeMatching.inl>:
s:#include *[<"]sofa/component/engine/ShapeMatching.h[>"]:#include <SofaEngine/ShapeMatching.h>:
s:#include *[<"]sofa/component/engine/ClusteringEngine.inl[>"]:#include <SofaEngine/ClusteringEngine.inl>:
s:#include *[<"]sofa/component/engine/ClusteringEngine.h[>"]:#include <SofaEngine/ClusteringEngine.h>:
s:#include *[<"]sofa/component/engine/NormalsFromPoints.inl[>"]:#include <SofaEngine/NormalsFromPoints.inl>:
s:#include *[<"]sofa/component/engine/NormalsFromPoints.h[>"]:#include <SofaEngine/NormalsFromPoints.h>:
s:#include *[<"]sofa/component/engine/ValuesFromPositions.inl[>"]:#include <SofaEngine/ValuesFromPositions.inl>:
s:#include *[<"]sofa/component/engine/ValuesFromPositions.h[>"]:#include <SofaEngine/ValuesFromPositions.h>:
s:#include *[<"]sofa/component/engine/QuatToRigidEngine.inl[>"]:#include <SofaEngine/QuatToRigidEngine.inl>:
s:#include *[<"]sofa/component/engine/QuatToRigidEngine.h[>"]:#include <SofaEngine/QuatToRigidEngine.h>:
s:#include *[<"]sofa/component/engine/RigidToQuatEngine.inl[>"]:#include <SofaEngine/RigidToQuatEngine.inl>:
s:#include *[<"]sofa/component/engine/RigidToQuatEngine.h[>"]:#include <SofaEngine/RigidToQuatEngine.h>:
s:#include *[<"]sofa/component/engine/SubsetTopology.inl[>"]:#include <SofaEngine/SubsetTopology.inl>:
s:#include *[<"]sofa/component/engine/SubsetTopology.h[>"]:#include <SofaEngine/SubsetTopology.h>:
s:#include *[<"]sofa/component/engine/TextureInterpolation.inl[>"]:#include <SofaEngine/TextureInterpolation.inl>:
s:#include *[<"]sofa/component/engine/TextureInterpolation.h[>"]:#include <SofaEngine/TextureInterpolation.h>:
s:#include *[<"]sofa/component/engine/Vertex2Frame.inl[>"]:#include <SofaEngine/Vertex2Frame.inl>:
s:#include *[<"]sofa/component/engine/Vertex2Frame.h[>"]:#include <SofaEngine/Vertex2Frame.h>:
s:#include *[<"]sofa/component/engine/Spiral.inl[>"]:#include <SofaEngine/Spiral.inl>:
s:#include *[<"]sofa/component/engine/Spiral.h[>"]:#include <SofaEngine/Spiral.h>:
s:#include *[<"]sofa/component/engine/RandomPointDistributionInSurface.inl[>"]:#include <SofaEngine/RandomPointDistributionInSurface.inl>:
s:#include *[<"]sofa/component/engine/RandomPointDistributionInSurface.h[>"]:#include <SofaEngine/RandomPointDistributionInSurface.h>:
s:#include *[<"]sofa/component/engine/MapIndices.inl[>"]:#include <SofaEngine/MapIndices.inl>:
s:#include *[<"]sofa/component/engine/MapIndices.h[>"]:#include <SofaEngine/MapIndices.h>:
s:#include *[<"]sofa/component/engine/JoinPoints.inl[>"]:#include <SofaEngine/JoinPoints.inl>:
s:#include *[<"]sofa/component/engine/JoinPoints.h[>"]:#include <SofaEngine/JoinPoints.h>:
s:#include *[<"]sofa/component/engine/IndexValueMapper.inl[>"]:#include <SofaEngine/IndexValueMapper.inl>:
s:#include *[<"]sofa/component/engine/IndexValueMapper.h[>"]:#include <SofaEngine/IndexValueMapper.h>:
s:#include *[<"]sofa/component/engine/IndicesFromValues.inl[>"]:#include <SofaEngine/IndicesFromValues.inl>:
s:#include *[<"]sofa/component/engine/IndicesFromValues.h[>"]:#include <SofaEngine/IndicesFromValues.h>:
s:#include *[<"]sofa/component/engine/ValuesFromIndices.inl[>"]:#include <SofaEngine/ValuesFromIndices.inl>:
s:#include *[<"]sofa/component/engine/ValuesFromIndices.h[>"]:#include <SofaEngine/ValuesFromIndices.h>:
s:#include *[<"]sofa/component/engine/PointsFromIndices.inl[>"]:#include <SofaEngine/PointsFromIndices.inl>:
s:#include *[<"]sofa/component/engine/PointsFromIndices.h[>"]:#include <SofaEngine/PointsFromIndices.h>:
s:#include *[<"]sofa/component/engine/TransformEngine.inl[>"]:#include <SofaEngine/TransformEngine.inl>:
s:#include *[<"]sofa/component/engine/TransformEngine.h[>"]:#include <SofaEngine/TransformEngine.h>:
s:#include *[<"]sofa/component/engine/TransformPosition.inl[>"]:#include <SofaEngine/TransformPosition.inl>:
s:#include *[<"]sofa/component/engine/TransformPosition.h[>"]:#include <SofaEngine/TransformPosition.h>:
s:#include *[<"]sofa/component/engine/MeshROI.inl[>"]:#include <SofaEngine/MeshROI.inl>:
s:#include *[<"]sofa/component/engine/MeshROI.h[>"]:#include <SofaEngine/MeshROI.h>:
s:#include *[<"]sofa/component/engine/MeshBarycentricMapperEngine.inl[>"]:#include <SofaEngine/MeshBarycentricMapperEngine.inl>:
s:#include *[<"]sofa/component/engine/MeshBarycentricMapperEngine.h[>"]:#include <SofaEngine/MeshBarycentricMapperEngine.h>:
s:#include *[<"]sofa/component/engine/MergeVectors.inl[>"]:#include <SofaEngine/MergeVectors.inl>:
s:#include *[<"]sofa/component/engine/MergeVectors.h[>"]:#include <SofaEngine/MergeVectors.h>:
s:#include *[<"]sofa/component/engine/MergeSets.inl[>"]:#include <SofaEngine/MergeSets.inl>:
s:#include *[<"]sofa/component/engine/MergeSets.h[>"]:#include <SofaEngine/MergeSets.h>:
s:#include *[<"]sofa/component/engine/MergePoints.inl[>"]:#include <SofaEngine/MergePoints.inl>:
s:#include *[<"]sofa/component/engine/MergePoints.h[>"]:#include <SofaEngine/MergePoints.h>:
s:#include *[<"]sofa/component/engine/MergeMeshes.inl[>"]:#include <SofaEngine/MergeMeshes.inl>:
s:#include *[<"]sofa/component/engine/MergeMeshes.h[>"]:#include <SofaEngine/MergeMeshes.h>:
s:#include *[<"]sofa/component/engine/MathOp.inl[>"]:#include <SofaEngine/MathOp.inl>:
s:#include *[<"]sofa/component/engine/MathOp.h[>"]:#include <SofaEngine/MathOp.h>:
s:#include *[<"]sofa/component/engine/GroupFilterYoungModulus.inl[>"]:#include <SofaEngine/GroupFilterYoungModulus.inl>:
s:#include *[<"]sofa/component/engine/GroupFilterYoungModulus.h[>"]:#include <SofaEngine/GroupFilterYoungModulus.h>:
s:#include *[<"]sofa/component/engine/GenerateRigidMass.inl[>"]:#include <SofaEngine/GenerateRigidMass.inl>:
s:#include *[<"]sofa/component/engine/GenerateRigidMass.h[>"]:#include <SofaEngine/GenerateRigidMass.h>:
s:#include *[<"]sofa/component/engine/ExtrudeEdgesAndGenerateQuads.inl[>"]:#include <SofaEngine/ExtrudeEdgesAndGenerateQuads.inl>:
s:#include *[<"]sofa/component/engine/ExtrudeEdgesAndGenerateQuads.h[>"]:#include <SofaEngine/ExtrudeEdgesAndGenerateQuads.h>:
s:#include *[<"]sofa/component/engine/ExtrudeQuadsAndGenerateHexas.inl[>"]:#include <SofaEngine/ExtrudeQuadsAndGenerateHexas.inl>:
s:#include *[<"]sofa/component/engine/ExtrudeQuadsAndGenerateHexas.h[>"]:#include <SofaEngine/ExtrudeQuadsAndGenerateHexas.h>:
s:#include *[<"]sofa/component/engine/ExtrudeSurface.inl[>"]:#include <SofaEngine/ExtrudeSurface.inl>:
s:#include *[<"]sofa/component/engine/ExtrudeSurface.h[>"]:#include <SofaEngine/ExtrudeSurface.h>:
s:#include *[<"]sofa/component/engine/DilateEngine.inl[>"]:#include <SofaEngine/DilateEngine.inl>:
s:#include *[<"]sofa/component/engine/DilateEngine.h[>"]:#include <SofaEngine/DilateEngine.h>:
s:#include *[<"]sofa/component/engine/SphereROI.inl[>"]:#include <SofaEngine/SphereROI.inl>:
s:#include *[<"]sofa/component/engine/SphereROI.h[>"]:#include <SofaEngine/SphereROI.h>:
s:#include *[<"]sofa/component/engine/PlaneROI.inl[>"]:#include <SofaEngine/PlaneROI.inl>:
s:#include *[<"]sofa/component/engine/PlaneROI.h[>"]:#include <SofaEngine/PlaneROI.h>:
s:#include *[<"]sofa/component/engine/PairBoxRoi.inl[>"]:#include <SofaEngine/PairBoxRoi.inl>:
s:#include *[<"]sofa/component/engine/PairBoxRoi.h[>"]:#include <SofaEngine/PairBoxRoi.h>:
s:#include *[<"]sofa/component/engine/BoxROI.inl[>"]:#include <SofaEngine/BoxROI.inl>:
s:#include *[<"]sofa/component/engine/BoxROI.h[>"]:#include <SofaEngine/BoxROI.h>:
s:#include *[<"]sofa/component/engine/AverageCoord.inl[>"]:#include <SofaEngine/AverageCoord.inl>:
s:#include *[<"]sofa/component/engine/AverageCoord.h[>"]:#include <SofaEngine/AverageCoord.h>:
s:#include *[<"]sofa/component/behaviormodel/eulerianfluid/Grid3D.h[>"]:#include <SofaEulerianFluid/Grid3D.h>:
s:#include *[<"]sofa/component/behaviormodel/eulerianfluid/Grid2D.h[>"]:#include <SofaEulerianFluid/Grid2D.h>:
s:#include *[<"]sofa/component/behaviormodel/eulerianfluid/Fluid3D.h[>"]:#include <SofaEulerianFluid/Fluid3D.h>:
s:#include *[<"]sofa/component/behaviormodel/eulerianfluid/Fluid2D.h[>"]:#include <SofaEulerianFluid/Fluid2D.h>:
s:#include *[<"]sofa/component/odesolver/RungeKutta4Solver.h[>"]:#include <SofaExplicitOdeSolver/RungeKutta4Solver.h>:
s:#include *[<"]sofa/component/odesolver/RungeKutta2Solver.h[>"]:#include <SofaExplicitOdeSolver/RungeKutta2Solver.h>:
s:#include *[<"]sofa/component/odesolver/EulerSolver.h[>"]:#include <SofaExplicitOdeSolver/EulerSolver.h>:
s:#include *[<"]sofa/component/odesolver/CentralDifferenceSolver.h[>"]:#include <SofaExplicitOdeSolver/CentralDifferenceSolver.h>:
s:#include *[<"]sofa/component/misc/MeshExporter.h[>"]:#include <SofaExporter/MeshExporter.h>:
s:#include *[<"]sofa/component/misc/STLExporter.h[>"]:#include <SofaExporter/STLExporter.h>:
s:#include *[<"]sofa/component/misc/OBJExporter.h[>"]:#include <SofaExporter/OBJExporter.h>:
s:#include *[<"]sofa/component/misc/VTKExporter.h[>"]:#include <SofaExporter/VTKExporter.h>:
s:#include *[<"]sofa/component/misc/WriteTopology.inl[>"]:#include <SofaExporter/WriteTopology.inl>:
s:#include *[<"]sofa/component/misc/WriteTopology.h[>"]:#include <SofaExporter/WriteTopology.h>:
s:#include *[<"]sofa/component/misc/WriteState.inl[>"]:#include <SofaExporter/WriteState.inl>:
s:#include *[<"]sofa/component/misc/WriteState.h[>"]:#include <SofaExporter/WriteState.h>:
s:#include *[<"]sofa/component/controller/MechanicalStateForceFeedback.h[>"]:#include <SofaHaptics/MechanicalStateForceFeedback.h>:
s:#include *[<"]sofa/component/controller/LCPForceFeedback.inl[>"]:#include <SofaHaptics/LCPForceFeedback.inl>:
s:#include *[<"]sofa/component/controller/LCPForceFeedback.h[>"]:#include <SofaHaptics/LCPForceFeedback.h>:
s:#include *[<"]sofa/component/controller/NullForceFeedback.h[>"]:#include <SofaHaptics/NullForceFeedback.h>:
s:#include *[<"]sofa/component/controller/NullForceFeedbackT.h[>"]:#include <SofaHaptics/NullForceFeedbackT.h>:
s:#include *[<"]sofa/component/controller/ForceFeedback.h[>"]:#include <SofaHaptics/ForceFeedback.h>:
s:#include *[<"]sofa/component/odesolver/StaticSolver.h[>"]:#include <SofaImplicitOdeSolver/StaticSolver.h>:
s:#include *[<"]sofa/component/odesolver/EulerImplicitSolver.h[>"]:#include <SofaImplicitOdeSolver/EulerImplicitSolver.h>:
s:#include *[<"]sofa/component/collision/DirectSAP.inl[>"]:#include <SofaMeshCollision/DirectSAP.inl>:
s:#include *[<"]sofa/component/collision/DirectSAP.h[>"]:#include <SofaMeshCollision/DirectSAP.h>:
s:#include *[<"]sofa/component/collision/IncrSAP.inl[>"]:#include <SofaMeshCollision/IncrSAP.inl>:
s:#include *[<"]sofa/component/collision/IncrSAP.h[>"]:#include <SofaMeshCollision/IncrSAP.h>:
s:#include *[<"]sofa/component/collision/IntrMeshUtility.inl[>"]:#include <SofaMeshCollision/IntrMeshUtility.inl>:
s:#include *[<"]sofa/component/collision/IntrMeshUtility.h[>"]:#include <SofaMeshCollision/IntrMeshUtility.h>:
s:#include *[<"]sofa/component/collision/IntrTriangleOBB.inl[>"]:#include <SofaMeshCollision/IntrTriangleOBB.inl>:
s:#include *[<"]sofa/component/collision/IntrTriangleOBB.h[>"]:#include <SofaMeshCollision/IntrTriangleOBB.h>:
s:#include *[<"]sofa/component/collision/MeshIntTool.inl[>"]:#include <SofaMeshCollision/MeshIntTool.inl>:
s:#include *[<"]sofa/component/collision/MeshIntTool.h[>"]:#include <SofaMeshCollision/MeshIntTool.h>:
s:#include *[<"]sofa/component/collision/LocalMinDistanceFilter.h[>"]:#include <SofaMeshCollision/LocalMinDistanceFilter.h>:
s:#include *[<"]sofa/component/collision/TriangleLocalMinDistanceFilter.h[>"]:#include <SofaMeshCollision/TriangleLocalMinDistanceFilter.h>:
s:#include *[<"]sofa/component/collision/LineLocalMinDistanceFilter.h[>"]:#include <SofaMeshCollision/LineLocalMinDistanceFilter.h>:
s:#include *[<"]sofa/component/collision/PointLocalMinDistanceFilter.h[>"]:#include <SofaMeshCollision/PointLocalMinDistanceFilter.h>:
s:#include *[<"]sofa/component/collision/RayTriangleIntersection.h[>"]:#include <SofaMeshCollision/RayTriangleIntersection.h>:
s:#include *[<"]sofa/component/collision/TriangleOctreeModel.h[>"]:#include <SofaMeshCollision/TriangleOctreeModel.h>:
s:#include *[<"]sofa/component/collision/TriangleOctree.h[>"]:#include <SofaMeshCollision/TriangleOctree.h>:
s:#include *[<"]sofa/component/collision/TriangleModel.inl[>"]:#include <SofaMeshCollision/TriangleModel.inl>:
s:#include *[<"]sofa/component/collision/TriangleModel.h[>"]:#include <SofaMeshCollision/TriangleModel.h>:
s:#include *[<"]sofa/component/collision/Triangle.h[>"]:#include <SofaMeshCollision/Triangle.h>:
s:#include *[<"]sofa/component/collision/LineModel.inl[>"]:#include <SofaMeshCollision/LineModel.inl>:
s:#include *[<"]sofa/component/collision/LineModel.h[>"]:#include <SofaMeshCollision/LineModel.h>:
s:#include *[<"]sofa/component/collision/Line.h[>"]:#include <SofaMeshCollision/Line.h>:
s:#include *[<"]sofa/component/collision/PointModel.inl[>"]:#include <SofaMeshCollision/PointModel.inl>:
s:#include *[<"]sofa/component/collision/PointModel.h[>"]:#include <SofaMeshCollision/PointModel.h>:
s:#include *[<"]sofa/component/collision/Point.h[>"]:#include <SofaMeshCollision/Point.h>:
s:#include *[<"]sofa/component/collision/MeshMinProximityIntersection.h[>"]:#include <SofaMeshCollision/MeshMinProximityIntersection.h>:
s:#include *[<"]sofa/component/collision/MeshDiscreteIntersection.inl[>"]:#include <SofaMeshCollision/MeshDiscreteIntersection.inl>:
s:#include *[<"]sofa/component/collision/MeshDiscreteIntersection.h[>"]:#include <SofaMeshCollision/MeshDiscreteIntersection.h>:
s:#include *[<"]sofa/component/collision/SubsetContactMapper.inl[>"]:#include <SofaMeshCollision/SubsetContactMapper.inl>:
s:#include *[<"]sofa/component/collision/SubsetContactMapper.h[>"]:#include <SofaMeshCollision/SubsetContactMapper.h>:
s:#include *[<"]sofa/component/collision/RigidContactMapper.inl[>"]:#include <SofaMeshCollision/RigidContactMapper.inl>:
s:#include *[<"]sofa/component/collision/RigidContactMapper.h[>"]:#include <SofaMeshCollision/RigidContactMapper.h>:
s:#include *[<"]sofa/component/collision/IdentityContactMapper.inl[>"]:#include <SofaMeshCollision/IdentityContactMapper.inl>:
s:#include *[<"]sofa/component/collision/IdentityContactMapper.h[>"]:#include <SofaMeshCollision/IdentityContactMapper.h>:
s:#include *[<"]sofa/component/collision/BarycentricContactMapper.inl[>"]:#include <SofaMeshCollision/BarycentricContactMapper.inl>:
s:#include *[<"]sofa/component/collision/BarycentricContactMapper.h[>"]:#include <SofaMeshCollision/BarycentricContactMapper.h>:
s:#include *[<"]sofa/component/collision/BarycentricPenalityContact.inl[>"]:#include <SofaMeshCollision/BarycentricPenalityContact.inl>:
s:#include *[<"]sofa/component/collision/BarycentricPenalityContact.h[>"]:#include <SofaMeshCollision/BarycentricPenalityContact.h>:
s:#include *[<"]sofa/component/collision/MeshNewProximityIntersection.inl[>"]:#include <SofaMeshCollision/MeshNewProximityIntersection.inl>:
s:#include *[<"]sofa/component/collision/MeshNewProximityIntersection.h[>"]:#include <SofaMeshCollision/MeshNewProximityIntersection.h>:
s:#include *[<"]sofa/component/linearsolver/ParallelCGLinearSolver.inl[>"]:#include <SofaMisc/ParallelCGLinearSolver.inl>:
s:#include *[<"]sofa/component/linearsolver/ParallelCGLinearSolver.h[>"]:#include <SofaMisc/ParallelCGLinearSolver.h>:
s:#include *[<"]sofa/component/misc/MeshTetraStuffing.h[>"]:#include <SofaMisc/MeshTetraStuffing.h>:
s:#include *[<"]sofa/component/collision/ParallelCollisionPipeline.h[>"]:#include <SofaMiscCollision/ParallelCollisionPipeline.h>:
s:#include *[<"]sofa/component/collision/BarycentricStickContact.inl[>"]:#include <SofaMiscCollision/BarycentricStickContact.inl>:
s:#include *[<"]sofa/component/collision/BarycentricStickContact.h[>"]:#include <SofaMiscCollision/BarycentricStickContact.h>:
s:#include *[<"]sofa/component/collision/TetrahedronModel.h[>"]:#include <SofaMiscCollision/TetrahedronModel.h>:
s:#include *[<"]sofa/component/collision/SpatialGridPointModel.h[>"]:#include <SofaMiscCollision/SpatialGridPointModel.h>:
s:#include *[<"]sofa/component/collision/TetrahedronDiscreteIntersection.h[>"]:#include <SofaMiscCollision/TetrahedronDiscreteIntersection.h>:
s:#include *[<"]sofa/component/collision/SolverMerger.h[>"]:#include <SofaMiscCollision/SolverMerger.h>:
s:#include *[<"]sofa/component/collision/DefaultCollisionGroupManager.h[>"]:#include <SofaMiscCollision/DefaultCollisionGroupManager.h>:
s:#include *[<"]sofa/component/collision/RuleBasedContactManager.h[>"]:#include <SofaMiscCollision/RuleBasedContactManager.h>:
s:#include *[<"]sofa/component/collision/TriangleModelInRegularGrid.h[>"]:#include <SofaMiscCollision/TriangleModelInRegularGrid.h>:
s:#include *[<"]sofa/component/engine/ProjectiveTransformEngine.inl[>"]:#include <SofaMiscEngine/ProjectiveTransformEngine.inl>:
s:#include *[<"]sofa/component/engine/ProjectiveTransformEngine.h[>"]:#include <SofaMiscEngine/ProjectiveTransformEngine.h>:
s:#include *[<"]sofa/component/engine/Distances.inl[>"]:#include <SofaMiscEngine/Distances.inl>:
s:#include *[<"]sofa/component/engine/Distances.h[>"]:#include <SofaMiscEngine/Distances.h>:
s:#include *[<"]sofa/component/fem/material/VerondaWestman.h[>"]:#include <SofaMiscFem/VerondaWestman.h>:
s:#include *[<"]sofa/component/fem/material/STVenantKirchhoff.h[>"]:#include <SofaMiscFem/STVenantKirchhoff.h>:
s:#include *[<"]sofa/component/fem/material/PlasticMaterial.h[>"]:#include <SofaMiscFem/PlasticMaterial.h>:
s:#include *[<"]sofa/component/fem/material/MooneyRivlin.h[>"]:#include <SofaMiscFem/MooneyRivlin.h>:
s:#include *[<"]sofa/component/fem/material/HyperelasticMaterial.h[>"]:#include <SofaMiscFem/HyperelasticMaterial.h>:
s:#include *[<"]sofa/component/fem/material/Costa.h[>"]:#include <SofaMiscFem/Costa.h>:
s:#include *[<"]sofa/component/fem/material/BoyceAndArruda.h[>"]:#include <SofaMiscFem/BoyceAndArruda.h>:
s:#include *[<"]sofa/component/forcefield/StandardTetrahedralFEMForceField.inl[>"]:#include <SofaMiscFem/StandardTetrahedralFEMForceField.inl>:
s:#include *[<"]sofa/component/forcefield/StandardTetrahedralFEMForceField.h[>"]:#include <SofaMiscFem/StandardTetrahedralFEMForceField.h>:
s:#include *[<"]sofa/component/forcefield/TetrahedralTensorMassForceField.inl[>"]:#include <SofaMiscFem/TetrahedralTensorMassForceField.inl>:
s:#include *[<"]sofa/component/forcefield/TetrahedralTensorMassForceField.h[>"]:#include <SofaMiscFem/TetrahedralTensorMassForceField.h>:
s:#include *[<"]sofa/component/forcefield/FastTetrahedralCorotationalForceField.inl[>"]:#include <SofaMiscFem/FastTetrahedralCorotationalForceField.inl>:
s:#include *[<"]sofa/component/forcefield/FastTetrahedralCorotationalForceField.h[>"]:#include <SofaMiscFem/FastTetrahedralCorotationalForceField.h>:
s:#include *[<"]sofa/component/interactionforcefield/LineBendingSprings.inl[>"]:#include <SofaMiscForceField/LineBendingSprings.inl>:
s:#include *[<"]sofa/component/interactionforcefield/LineBendingSprings.h[>"]:#include <SofaMiscForceField/LineBendingSprings.h>:
s:#include *[<"]sofa/component/interactionforcefield/GearSpringForceField.inl[>"]:#include <SofaMiscForceField/GearSpringForceField.inl>:
s:#include *[<"]sofa/component/interactionforcefield/GearSpringForceField.h[>"]:#include <SofaMiscForceField/GearSpringForceField.h>:
s:#include *[<"]sofa/component/forcefield/WashingMachineForceField.inl[>"]:#include <SofaMiscForceField/WashingMachineForceField.inl>:
s:#include *[<"]sofa/component/forcefield/WashingMachineForceField.h[>"]:#include <SofaMiscForceField/WashingMachineForceField.h>:
s:#include *[<"]sofa/component/forcefield/LennardJonesForceField.inl[>"]:#include <SofaMiscForceField/LennardJonesForceField.inl>:
s:#include *[<"]sofa/component/forcefield/LennardJonesForceField.h[>"]:#include <SofaMiscForceField/LennardJonesForceField.h>:
s:#include *[<"]sofa/component/mass/MeshMatrixMass.inl[>"]:#include <SofaMiscForceField/MeshMatrixMass.inl>:
s:#include *[<"]sofa/component/mass/MeshMatrixMass.h[>"]:#include <SofaMiscForceField/MeshMatrixMass.h>:
s:#include *[<"]sofa/component/mass/MatrixMass.inl[>"]:#include <SofaMiscForceField/MatrixMass.inl>:
s:#include *[<"]sofa/component/mass/MatrixMass.h[>"]:#include <SofaMiscForceField/MatrixMass.h>:
s:#include *[<"]sofa/component/mapping/CatmullRomSplineMapping.inl[>"]:#include <SofaMiscMapping/CatmullRomSplineMapping.inl>:
s:#include *[<"]sofa/component/mapping/CatmullRomSplineMapping.h[>"]:#include <SofaMiscMapping/CatmullRomSplineMapping.h>:
s:#include *[<"]sofa/component/mapping/PCAOnRigidFrameMapping.inl[>"]:#include <SofaMiscMapping/PCAOnRigidFrameMapping.inl>:
s:#include *[<"]sofa/component/mapping/PCAOnRigidFrameMapping.h[>"]:#include <SofaMiscMapping/PCAOnRigidFrameMapping.h>:
s:#include *[<"]sofa/component/mapping/DeformableOnRigidFrameMapping.inl[>"]:#include <SofaMiscMapping/DeformableOnRigidFrameMapping.inl>:
s:#include *[<"]sofa/component/mapping/DeformableOnRigidFrameMapping.h[>"]:#include <SofaMiscMapping/DeformableOnRigidFrameMapping.h>:
s:#include *[<"]sofa/component/mapping/BarycentricMappingRigid.inl[>"]:#include <SofaMiscMapping/BarycentricMappingRigid.inl>:
s:#include *[<"]sofa/component/mapping/BarycentricMappingRigid.h[>"]:#include <SofaMiscMapping/BarycentricMappingRigid.h>:
s:#include *[<"]sofa/component/mapping/VoidMapping.h[>"]:#include <SofaMiscMapping/VoidMapping.h>:
s:#include *[<"]sofa/component/mapping/TubularMapping.inl[>"]:#include <SofaMiscMapping/TubularMapping.inl>:
s:#include *[<"]sofa/component/mapping/TubularMapping.h[>"]:#include <SofaMiscMapping/TubularMapping.h>:
s:#include *[<"]sofa/component/mapping/SubsetMultiMapping.inl[>"]:#include <SofaMiscMapping/SubsetMultiMapping.inl>:
s:#include *[<"]sofa/component/mapping/SubsetMultiMapping.h[>"]:#include <SofaMiscMapping/SubsetMultiMapping.h>:
s:#include *[<"]sofa/component/mapping/ExternalInterpolationMapping.inl[>"]:#include <SofaMiscMapping/ExternalInterpolationMapping.inl>:
s:#include *[<"]sofa/component/mapping/ExternalInterpolationMapping.h[>"]:#include <SofaMiscMapping/ExternalInterpolationMapping.h>:
s:#include *[<"]sofa/component/mapping/DistanceFromTargetMapping.inl[>"]:#include <SofaMiscMapping/DistanceFromTargetMapping.inl>:
s:#include *[<"]sofa/component/mapping/DistanceFromTargetMapping.h[>"]:#include <SofaMiscMapping/DistanceFromTargetMapping.h>:
s:#include *[<"]sofa/component/mapping/DistanceMapping.inl[>"]:#include <SofaMiscMapping/DistanceMapping.inl>:
s:#include *[<"]sofa/component/mapping/DistanceMapping.h[>"]:#include <SofaMiscMapping/DistanceMapping.h>:
s:#include *[<"]sofa/component/mapping/CurveMapping.inl[>"]:#include <SofaMiscMapping/CurveMapping.inl>:
s:#include *[<"]sofa/component/mapping/CurveMapping.h[>"]:#include <SofaMiscMapping/CurveMapping.h>:
s:#include *[<"]sofa/component/mapping/CenterOfMassMulti2Mapping.inl[>"]:#include <SofaMiscMapping/CenterOfMassMulti2Mapping.inl>:
s:#include *[<"]sofa/component/mapping/CenterOfMassMulti2Mapping.h[>"]:#include <SofaMiscMapping/CenterOfMassMulti2Mapping.h>:
s:#include *[<"]sofa/component/mapping/CenterOfMassMultiMapping.inl[>"]:#include <SofaMiscMapping/CenterOfMassMultiMapping.inl>:
s:#include *[<"]sofa/component/mapping/CenterOfMassMultiMapping.h[>"]:#include <SofaMiscMapping/CenterOfMassMultiMapping.h>:
s:#include *[<"]sofa/component/mapping/CenterOfMassMapping.inl[>"]:#include <SofaMiscMapping/CenterOfMassMapping.inl>:
s:#include *[<"]sofa/component/mapping/CenterOfMassMapping.h[>"]:#include <SofaMiscMapping/CenterOfMassMapping.h>:
s:#include *[<"]sofa/component/mapping/CenterPointMechanicalMapping.inl[>"]:#include <SofaMiscMapping/CenterPointMechanicalMapping.inl>:
s:#include *[<"]sofa/component/mapping/CenterPointMechanicalMapping.h[>"]:#include <SofaMiscMapping/CenterPointMechanicalMapping.h>:
s:#include *[<"]sofa/component/mapping/BeamLinearMapping.inl[>"]:#include <SofaMiscMapping/BeamLinearMapping.inl>:
s:#include *[<"]sofa/component/mapping/BeamLinearMapping.h[>"]:#include <SofaMiscMapping/BeamLinearMapping.h>:
s:#include *[<"]sofa/component/odesolver/NewmarkImplicitSolver.h[>"]:#include <SofaMiscSolver/NewmarkImplicitSolver.h>:
s:#include *[<"]sofa/component/odesolver/DampVelocitySolver.h[>"]:#include <SofaMiscSolver/DampVelocitySolver.h>:
s:#include *[<"]sofa/component/misc/TopologicalChangeProcessor.h[>"]:#include <SofaMiscTopology/TopologicalChangeProcessor.h>:
s:#include *[<"]sofa/component/interactionforcefield/RepulsiveSpringForceField.inl[>"]:#include <SofaObjectInteraction/RepulsiveSpringForceField.inl>:
s:#include *[<"]sofa/component/interactionforcefield/RepulsiveSpringForceField.h[>"]:#include <SofaObjectInteraction/RepulsiveSpringForceField.h>:
s:#include *[<"]sofa/component/interactionforcefield/PenalityContactForceField.inl[>"]:#include <SofaObjectInteraction/PenalityContactForceField.inl>:
s:#include *[<"]sofa/component/interactionforcefield/PenalityContactForceField.h[>"]:#include <SofaObjectInteraction/PenalityContactForceField.h>:
s:#include *[<"]sofa/component/interactionforcefield/InteractionEllipsoidForceField.inl[>"]:#include <SofaObjectInteraction/InteractionEllipsoidForceField.inl>:
s:#include *[<"]sofa/component/interactionforcefield/InteractionEllipsoidForceField.h[>"]:#include <SofaObjectInteraction/InteractionEllipsoidForceField.h>:
s:#include *[<"]sofa/component/interactionforcefield/BoxStiffSpringForceField.inl[>"]:#include <SofaObjectInteraction/BoxStiffSpringForceField.inl>:
s:#include *[<"]sofa/component/interactionforcefield/BoxStiffSpringForceField.h[>"]:#include <SofaObjectInteraction/BoxStiffSpringForceField.h>:
s:#include *[<"]sofa/component/projectiveconstraintset/AttachConstraint.inl[>"]:#include <SofaObjectInteraction/AttachConstraint.inl>:
s:#include *[<"]sofa/component/projectiveconstraintset/AttachConstraint.h[>"]:#include <SofaObjectInteraction/AttachConstraint.h>:
s:#include *[<"]sofa/component/visualmodel/VisualManagerSecondaryPass.h[>"]:#include <SofaOpenglVisual/VisualManagerSecondaryPass.h>:
s:#include *[<"]sofa/component/visualmodel/VisualManagerPass.h[>"]:#include <SofaOpenglVisual/VisualManagerPass.h>:
s:#include *[<"]sofa/component/visualmodel/SlicedVolumetricModel.h[>"]:#include <SofaOpenglVisual/SlicedVolumetricModel.h>:
s:#include *[<"]sofa/component/visualmodel/PostProcessManager.h[>"]:#include <SofaOpenglVisual/PostProcessManager.h>:
s:#include *[<"]sofa/component/visualmodel/OglVariable.inl[>"]:#include <SofaOpenglVisual/OglVariable.inl>:
s:#include *[<"]sofa/component/visualmodel/OglVariable.h[>"]:#include <SofaOpenglVisual/OglVariable.h>:
s:#include *[<"]sofa/component/visualmodel/OglTexture.h[>"]:#include <SofaOpenglVisual/OglTexture.h>:
s:#include *[<"]sofa/component/visualmodel/OglTetrahedralModel.inl[>"]:#include <SofaOpenglVisual/OglTetrahedralModel.inl>:
s:#include *[<"]sofa/component/visualmodel/OglTetrahedralModel.h[>"]:#include <SofaOpenglVisual/OglTetrahedralModel.h>:
s:#include *[<"]sofa/component/visualmodel/OglShadowShader.h[>"]:#include <SofaOpenglVisual/OglShadowShader.h>:
s:#include *[<"]sofa/component/visualmodel/OglShaderVisualModel.h[>"]:#include <SofaOpenglVisual/OglShaderVisualModel.h>:
s:#include *[<"]sofa/component/visualmodel/OglShaderMacro.h[>"]:#include <SofaOpenglVisual/OglShaderMacro.h>:
s:#include *[<"]sofa/component/visualmodel/OglShader.h[>"]:#include <SofaOpenglVisual/OglShader.h>:
s:#include *[<"]sofa/component/visualmodel/OglAttribute.inl[>"]:#include <SofaOpenglVisual/OglAttribute.inl>:
s:#include *[<"]sofa/component/visualmodel/OglAttribute.h[>"]:#include <SofaOpenglVisual/OglAttribute.h>:
s:#include *[<"]sofa/component/visualmodel/OglCylinderModel.h[>"]:#include <SofaOpenglVisual/OglCylinderModel.h>:
s:#include *[<"]sofa/component/visualmodel/OglLabel.h[>"]:#include <SofaOpenglVisual/OglLabel.h>:
s:#include *[<"]sofa/component/visualmodel/DataDisplay.h[>"]:#include <SofaOpenglVisual/DataDisplay.h>:
s:#include *[<"]sofa/component/visualmodel/ColorMap.h[>"]:#include <SofaOpenglVisual/ColorMap.h>:
s:#include *[<"]sofa/component/visualmodel/CompositingVisualLoop.h[>"]:#include <SofaOpenglVisual/CompositingVisualLoop.h>:
s:#include *[<"]sofa/component/visualmodel/ClipPlane.h[>"]:#include <SofaOpenglVisual/ClipPlane.h>:
s:#include *[<"]sofa/component/visualmodel/OglRenderingSRGB.h[>"]:#include <SofaOpenglVisual/OglRenderingSRGB.h>:
s:#include *[<"]sofa/component/visualmodel/PointSplatModel.h[>"]:#include <SofaOpenglVisual/PointSplatModel.h>:
s:#include *[<"]sofa/component/visualmodel/LightManager.h[>"]:#include <SofaOpenglVisual/LightManager.h>:
s:#include *[<"]sofa/component/visualmodel/Light.h[>"]:#include <SofaOpenglVisual/Light.h>:
s:#include *[<"]sofa/component/visualmodel/OglViewport.h[>"]:#include <SofaOpenglVisual/OglViewport.h>:
s:#include *[<"]sofa/component/visualmodel/OglModel.h[>"]:#include <SofaOpenglVisual/OglModel.h>:
s:#include *[<"]sofa/component/linearsolver/SparsePARDISOSolver.h[>"]:#include <SofaPardisoSolver/SparsePARDISOSolver.h>:
s:#include *[<"]sofa/component/linearsolver/PrecomputedWarpPreconditioner.inl[>"]:#include <SofaPreconditioner/PrecomputedWarpPreconditioner.inl>:
s:#include *[<"]sofa/component/linearsolver/PrecomputedWarpPreconditioner.h[>"]:#include <SofaPreconditioner/PrecomputedWarpPreconditioner.h>:
s:#include *[<"]sofa/component/linearsolver/WarpPreconditioner.inl[>"]:#include <SofaPreconditioner/WarpPreconditioner.inl>:
s:#include *[<"]sofa/component/linearsolver/WarpPreconditioner.h[>"]:#include <SofaPreconditioner/WarpPreconditioner.h>:
s:#include *[<"]sofa/component/linearsolver/SSORPreconditioner.inl[>"]:#include <SofaPreconditioner/SSORPreconditioner.inl>:
s:#include *[<"]sofa/component/linearsolver/SSORPreconditioner.h[>"]:#include <SofaPreconditioner/SSORPreconditioner.h>:
s:#include *[<"]sofa/component/linearsolver/BlockJacobiPreconditioner.inl[>"]:#include <SofaPreconditioner/BlockJacobiPreconditioner.inl>:
s:#include *[<"]sofa/component/linearsolver/BlockJacobiPreconditioner.h[>"]:#include <SofaPreconditioner/BlockJacobiPreconditioner.h>:
s:#include *[<"]sofa/component/linearsolver/JacobiPreconditioner.inl[>"]:#include <SofaPreconditioner/JacobiPreconditioner.inl>:
s:#include *[<"]sofa/component/linearsolver/JacobiPreconditioner.h[>"]:#include <SofaPreconditioner/JacobiPreconditioner.h>:
s:#include *[<"]sofa/component/linearsolver/ShewchukPCGLinearSolver.h[>"]:#include <SofaPreconditioner/ShewchukPCGLinearSolver.h>:
s:#include *[<"]sofa/component/interactionforcefield/JointSpringForceField.inl[>"]:#include <SofaRigid/JointSpringForceField.inl>:
s:#include *[<"]sofa/component/interactionforcefield/JointSpringForceField.h[>"]:#include <SofaRigid/JointSpringForceField.h>:
s:#include *[<"]sofa/component/mapping/SkinningMapping.inl[>"]:#include <SofaRigid/SkinningMapping.inl>:
s:#include *[<"]sofa/component/mapping/SkinningMapping.h[>"]:#include <SofaRigid/SkinningMapping.h>:
s:#include *[<"]sofa/component/mapping/RigidRigidMapping.inl[>"]:#include <SofaRigid/RigidRigidMapping.inl>:
s:#include *[<"]sofa/component/mapping/RigidRigidMapping.h[>"]:#include <SofaRigid/RigidRigidMapping.h>:
s:#include *[<"]sofa/component/mapping/RigidMapping.inl[>"]:#include <SofaRigid/RigidMapping.inl>:
s:#include *[<"]sofa/component/mapping/RigidMapping.h[>"]:#include <SofaRigid/RigidMapping.h>:
s:#include *[<"]sofa/component/mapping/LineSetSkinningMapping.inl[>"]:#include <SofaRigid/LineSetSkinningMapping.inl>:
s:#include *[<"]sofa/component/mapping/LineSetSkinningMapping.h[>"]:#include <SofaRigid/LineSetSkinningMapping.h>:
s:#include *[<"]sofa/component/mapping/LaparoscopicRigidMapping.inl[>"]:#include <SofaRigid/LaparoscopicRigidMapping.inl>:
s:#include *[<"]sofa/component/mapping/LaparoscopicRigidMapping.h[>"]:#include <SofaRigid/LaparoscopicRigidMapping.h>:
s:#include *[<"]sofa/component/mapping/ArticulatedSystemMapping.inl[>"]:#include <SofaRigid/ArticulatedSystemMapping.inl>:
s:#include *[<"]sofa/component/mapping/ArticulatedSystemMapping.h[>"]:#include <SofaRigid/ArticulatedSystemMapping.h>:
s:#include *[<"]sofa/component/container/ArticulatedHierarchyContainer.inl[>"]:#include <SofaRigid/ArticulatedHierarchyContainer.inl>:
s:#include *[<"]sofa/component/container/ArticulatedHierarchyContainer.h[>"]:#include <SofaRigid/ArticulatedHierarchyContainer.h>:
s:#include *[<"]sofa/component/linearsolver/SparseLDLSolver.inl[>"]:#include <SofaSparseSolver/SparseLDLSolver.inl>:
s:#include *[<"]sofa/component/linearsolver/SparseLDLSolver.h[>"]:#include <SofaSparseSolver/SparseLDLSolver.h>:
s:#include *[<"]sofa/component/linearsolver/SparseLDLSolverImpl.h[>"]:#include <SofaSparseSolver/SparseLDLSolverImpl.h>:
s:#include *[<"]sofa/component/linearsolver/SparseLUSolver.h[>"]:#include <SofaSparseSolver/SparseLUSolver.h>:
s:#include *[<"]sofa/component/linearsolver/SparseCholeskySolver.h[>"]:#include <SofaSparseSolver/SparseCholeskySolver.h>:
s:#include *[<"]sofa/component/linearsolver/PrecomputedLinearSolver.inl[>"]:#include <SofaSparseSolver/PrecomputedLinearSolver.inl>:
s:#include *[<"]sofa/component/linearsolver/PrecomputedLinearSolver.h[>"]:#include <SofaSparseSolver/PrecomputedLinearSolver.h>:
s:#include *[<"]sofa/component/forcefield/ParticlesRepulsionForceField.inl[>"]:#include <SofaSphFluid/ParticlesRepulsionForceField.inl>:
s:#include *[<"]sofa/component/forcefield/ParticlesRepulsionForceField.h[>"]:#include <SofaSphFluid/ParticlesRepulsionForceField.h>:
s:#include *[<"]sofa/component/misc/ParticleSource.h[>"]:#include <SofaSphFluid/ParticleSource.h>:
s:#include *[<"]sofa/component/misc/ParticleSink.h[>"]:#include <SofaSphFluid/ParticleSink.h>:
s:#include *[<"]sofa/component/mapping/SPHFluidSurfaceMapping.inl[>"]:#include <SofaSphFluid/SPHFluidSurfaceMapping.inl>:
s:#include *[<"]sofa/component/mapping/SPHFluidSurfaceMapping.h[>"]:#include <SofaSphFluid/SPHFluidSurfaceMapping.h>:
s:#include *[<"]sofa/component/forcefield/SPHFluidForceField.inl[>"]:#include <SofaSphFluid/SPHFluidForceField.inl>:
s:#include *[<"]sofa/component/forcefield/SPHFluidForceField.h[>"]:#include <SofaSphFluid/SPHFluidForceField.h>:
s:#include *[<"]sofa/component/container/SpatialGridContainer.inl[>"]:#include <SofaSphFluid/SpatialGridContainer.inl>:
s:#include *[<"]sofa/component/container/SpatialGridContainer.h[>"]:#include <SofaSphFluid/SpatialGridContainer.h>:
s:#include *[<"]sofa/component/linearsolver/SparseTAUCSLLtSolver.h[>"]:#include <SofaTaucsSolver/SparseTAUCSLLtSolver.h>:
s:#include *[<"]sofa/component/linearsolver/IncompleteTAUCSSolver.h[>"]:#include <SofaTaucsSolver/IncompleteTAUCSSolver.h>:
s:#include *[<"]sofa/component/linearsolver/SparseTAUCSSolver.h[>"]:#include <SofaTaucsSolver/SparseTAUCSSolver.h>:
s:#include *[<"]sofa/component/misc/DataController.h[>"]:#include <SofaValidation/DataController.h>:
s:#include *[<"]sofa/component/misc/DataMonitor.h[>"]:#include <SofaValidation/DataMonitor.h>:
s:#include *[<"]sofa/component/misc/EvalSurfaceDistance.inl[>"]:#include <SofaValidation/EvalSurfaceDistance.inl>:
s:#include *[<"]sofa/component/misc/EvalSurfaceDistance.h[>"]:#include <SofaValidation/EvalSurfaceDistance.h>:
s:#include *[<"]sofa/component/misc/EvalPointsDistance.inl[>"]:#include <SofaValidation/EvalPointsDistance.inl>:
s:#include *[<"]sofa/component/misc/EvalPointsDistance.h[>"]:#include <SofaValidation/EvalPointsDistance.h>:
s:#include *[<"]sofa/component/misc/Monitor.inl[>"]:#include <SofaValidation/Monitor.inl>:
s:#include *[<"]sofa/component/misc/Monitor.h[>"]:#include <SofaValidation/Monitor.h>:
s:#include *[<"]sofa/component/misc/ExtraMonitor.inl[>"]:#include <SofaValidation/ExtraMonitor.inl>:
s:#include *[<"]sofa/component/misc/ExtraMonitor.h[>"]:#include <SofaValidation/ExtraMonitor.h>:
s:#include *[<"]sofa/component/misc/DevMonitorManager.h[>"]:#include <SofaValidation/DevMonitorManager.h>:
s:#include *[<"]sofa/component/misc/DevTensionMonitor.inl[>"]:#include <SofaValidation/DevTensionMonitor.inl>:
s:#include *[<"]sofa/component/misc/DevTensionMonitor.h[>"]:#include <SofaValidation/DevTensionMonitor.h>:
s:#include *[<"]sofa/component/misc/DevAngleCollisionMonitor.inl[>"]:#include <SofaValidation/DevAngleCollisionMonitor.inl>:
s:#include *[<"]sofa/component/misc/DevAngleCollisionMonitor.h[>"]:#include <SofaValidation/DevAngleCollisionMonitor.h>:
s:#include *[<"]sofa/component/misc/CompareTopology.h[>"]:#include <SofaValidation/CompareTopology.h>:
s:#include *[<"]sofa/component/misc/CompareState.h[>"]:#include <SofaValidation/CompareState.h>:
s:#include *[<"]sofa/component/projectiveconstraintset/ProjectDirectionConstraint.inl[>"]:#include <SofaBoundaryCondition/ProjectDirectionConstraint.inl>:
s:#include *[<"]sofa/component/projectiveconstraintset/ProjectDirectionConstraint.h[>"]:#include <SofaBoundaryCondition/ProjectDirectionConstraint.h>:
s:#include *[<"]sofa/component/projectiveconstraintset/ProjectToPointConstraint.inl[>"]:#include <SofaBoundaryCondition/ProjectToPointConstraint.inl>:
s:#include *[<"]sofa/component/projectiveconstraintset/ProjectToPointConstraint.h[>"]:#include <SofaBoundaryCondition/ProjectToPointConstraint.h>:
s:#include *[<"]sofa/component/projectiveconstraintset/ProjectToPlaneConstraint.inl[>"]:#include <SofaBoundaryCondition/ProjectToPlaneConstraint.inl>:
s:#include *[<"]sofa/component/projectiveconstraintset/ProjectToPlaneConstraint.h[>"]:#include <SofaBoundaryCondition/ProjectToPlaneConstraint.h>:
s:#include *[<"]sofa/component/projectiveconstraintset/ProjectToLineConstraint.inl[>"]:#include <SofaBoundaryCondition/ProjectToLineConstraint.inl>:
s:#include *[<"]sofa/component/projectiveconstraintset/ProjectToLineConstraint.h[>"]:#include <SofaBoundaryCondition/ProjectToLineConstraint.h>:
s:#include *[<"]sofa/component/projectiveconstraintset/SkeletalMotionConstraint.inl[>"]:#include <SofaBoundaryCondition/SkeletalMotionConstraint.inl>:
s:#include *[<"]sofa/component/projectiveconstraintset/SkeletalMotionConstraint.h[>"]:#include <SofaBoundaryCondition/SkeletalMotionConstraint.h>:
s:#include *[<"]sofa/component/projectiveconstraintset/PositionBasedDynamicsConstraint.inl[>"]:#include <SofaBoundaryCondition/PositionBasedDynamicsConstraint.inl>:
s:#include *[<"]sofa/component/projectiveconstraintset/PositionBasedDynamicsConstraint.h[>"]:#include <SofaBoundaryCondition/PositionBasedDynamicsConstraint.h>:
s:#include *[<"]sofa/component/projectiveconstraintset/PointConstraint.inl[>"]:#include <SofaBoundaryCondition/PointConstraint.inl>:
s:#include *[<"]sofa/component/projectiveconstraintset/PointConstraint.h[>"]:#include <SofaBoundaryCondition/PointConstraint.h>:
s:#include *[<"]sofa/component/projectiveconstraintset/PartialLinearMovementConstraint.inl[>"]:#include <SofaBoundaryCondition/PartialLinearMovementConstraint.inl>:
s:#include *[<"]sofa/component/projectiveconstraintset/PartialLinearMovementConstraint.h[>"]:#include <SofaBoundaryCondition/PartialLinearMovementConstraint.h>:
s:#include *[<"]sofa/component/projectiveconstraintset/PartialFixedConstraint.inl[>"]:#include <SofaBoundaryCondition/PartialFixedConstraint.inl>:
s:#include *[<"]sofa/component/projectiveconstraintset/PartialFixedConstraint.h[>"]:#include <SofaBoundaryCondition/PartialFixedConstraint.h>:
s:#include *[<"]sofa/component/projectiveconstraintset/ParabolicConstraint.inl[>"]:#include <SofaBoundaryCondition/ParabolicConstraint.inl>:
s:#include *[<"]sofa/component/projectiveconstraintset/ParabolicConstraint.h[>"]:#include <SofaBoundaryCondition/ParabolicConstraint.h>:
s:#include *[<"]sofa/component/projectiveconstraintset/OscillatorConstraint.inl[>"]:#include <SofaBoundaryCondition/OscillatorConstraint.inl>:
s:#include *[<"]sofa/component/projectiveconstraintset/OscillatorConstraint.h[>"]:#include <SofaBoundaryCondition/OscillatorConstraint.h>:
s:#include *[<"]sofa/component/projectiveconstraintset/LinearVelocityConstraint.inl[>"]:#include <SofaBoundaryCondition/LinearVelocityConstraint.inl>:
s:#include *[<"]sofa/component/projectiveconstraintset/LinearVelocityConstraint.h[>"]:#include <SofaBoundaryCondition/LinearVelocityConstraint.h>:
s:#include *[<"]sofa/component/projectiveconstraintset/LinearMovementConstraint.inl[>"]:#include <SofaBoundaryCondition/LinearMovementConstraint.inl>:
s:#include *[<"]sofa/component/projectiveconstraintset/BilinearMovementConstraint.h[>"]:#include <SofaBoundaryCondition/BilinearMovementConstraint.h>:
s:#include *[<"]sofa/component/projectiveconstraintset/BilinearMovementConstraint.inl[>"]:#include <SofaBoundaryCondition/BilinearMovementConstraint.inl>:
s:#include *[<"]sofa/component/projectiveconstraintset/LinearMovementConstraint.h[>"]:#include <SofaBoundaryCondition/LinearMovementConstraint.h>:
s:#include *[<"]sofa/component/projectiveconstraintset/HermiteSplineConstraint.inl[>"]:#include <SofaBoundaryCondition/HermiteSplineConstraint.inl>:
s:#include *[<"]sofa/component/projectiveconstraintset/HermiteSplineConstraint.h[>"]:#include <SofaBoundaryCondition/HermiteSplineConstraint.h>:
s:#include *[<"]sofa/component/projectiveconstraintset/FixedTranslationConstraint.inl[>"]:#include <SofaBoundaryCondition/FixedTranslationConstraint.inl>:
s:#include *[<"]sofa/component/projectiveconstraintset/FixedTranslationConstraint.h[>"]:#include <SofaBoundaryCondition/FixedTranslationConstraint.h>:
s:#include *[<"]sofa/component/projectiveconstraintset/FixedRotationConstraint.inl[>"]:#include <SofaBoundaryCondition/FixedRotationConstraint.inl>:
s:#include *[<"]sofa/component/projectiveconstraintset/FixedRotationConstraint.h[>"]:#include <SofaBoundaryCondition/FixedRotationConstraint.h>:
s:#include *[<"]sofa/component/projectiveconstraintset/FixedPlaneConstraint.inl[>"]:#include <SofaBoundaryCondition/FixedPlaneConstraint.inl>:
s:#include *[<"]sofa/component/projectiveconstraintset/FixedPlaneConstraint.h[>"]:#include <SofaBoundaryCondition/FixedPlaneConstraint.h>:
s:#include *[<"]sofa/component/projectiveconstraintset/FixedConstraint.inl[>"]:#include <SofaBoundaryCondition/FixedConstraint.inl>:
s:#include *[<"]sofa/component/projectiveconstraintset/FixedConstraint.h[>"]:#include <SofaBoundaryCondition/FixedConstraint.h>:
s:#include *[<"]sofa/component/forcefield/VaccumSphereForceField.inl[>"]:#include <SofaBoundaryCondition/VaccumSphereForceField.inl>:
s:#include *[<"]sofa/component/forcefield/VaccumSphereForceField.h[>"]:#include <SofaBoundaryCondition/VaccumSphereForceField.h>:
s:#include *[<"]sofa/component/forcefield/TrianglePressureForceField.inl[>"]:#include <SofaBoundaryCondition/TrianglePressureForceField.inl>:
s:#include *[<"]sofa/component/forcefield/TrianglePressureForceField.h[>"]:#include <SofaBoundaryCondition/TrianglePressureForceField.h>:
s:#include *[<"]sofa/component/forcefield/TaitSurfacePressureForceField.inl[>"]:#include <SofaBoundaryCondition/TaitSurfacePressureForceField.inl>:
s:#include *[<"]sofa/component/forcefield/TaitSurfacePressureForceField.h[>"]:#include <SofaBoundaryCondition/TaitSurfacePressureForceField.h>:
s:#include *[<"]sofa/component/forcefield/SurfacePressureForceField.inl[>"]:#include <SofaBoundaryCondition/SurfacePressureForceField.inl>:
s:#include *[<"]sofa/component/forcefield/SurfacePressureForceField.h[>"]:#include <SofaBoundaryCondition/SurfacePressureForceField.h>:
s:#include *[<"]sofa/component/forcefield/SphereForceField.inl[>"]:#include <SofaBoundaryCondition/SphereForceField.inl>:
s:#include *[<"]sofa/component/forcefield/SphereForceField.h[>"]:#include <SofaBoundaryCondition/SphereForceField.h>:
s:#include *[<"]sofa/component/forcefield/PlaneForceField.inl[>"]:#include <SofaBoundaryCondition/PlaneForceField.inl>:
s:#include *[<"]sofa/component/forcefield/PlaneForceField.h[>"]:#include <SofaBoundaryCondition/PlaneForceField.h>:
s:#include *[<"]sofa/component/forcefield/OscillatingTorsionPressureForceField.inl[>"]:#include <SofaBoundaryCondition/OscillatingTorsionPressureForceField.inl>:
s:#include *[<"]sofa/component/forcefield/OscillatingTorsionPressureForceField.h[>"]:#include <SofaBoundaryCondition/OscillatingTorsionPressureForceField.h>:
s:#include *[<"]sofa/component/forcefield/LinearForceField.inl[>"]:#include <SofaBoundaryCondition/LinearForceField.inl>:
s:#include *[<"]sofa/component/forcefield/LinearForceField.h[>"]:#include <SofaBoundaryCondition/LinearForceField.h>:
s:#include *[<"]sofa/component/forcefield/EllipsoidForceField.inl[>"]:#include <SofaBoundaryCondition/EllipsoidForceField.inl>:
s:#include *[<"]sofa/component/forcefield/EllipsoidForceField.h[>"]:#include <SofaBoundaryCondition/EllipsoidForceField.h>:
s:#include *[<"]sofa/component/forcefield/EdgePressureForceField.inl[>"]:#include <SofaBoundaryCondition/EdgePressureForceField.inl>:
s:#include *[<"]sofa/component/forcefield/EdgePressureForceField.h[>"]:#include <SofaBoundaryCondition/EdgePressureForceField.h>:
s:#include *[<"]sofa/component/forcefield/ConstantForceField.inl[>"]:#include <SofaBoundaryCondition/ConstantForceField.inl>:
s:#include *[<"]sofa/component/forcefield/ConstantForceField.h[>"]:#include <SofaBoundaryCondition/ConstantForceField.h>:
s:#include *[<"]sofa/component/forcefield/ConicalForceField.inl[>"]:#include <SofaBoundaryCondition/ConicalForceField.inl>:
s:#include *[<"]sofa/component/forcefield/ConicalForceField.h[>"]:#include <SofaBoundaryCondition/ConicalForceField.h>:
s:#include *[<"]sofa/component/forcefield/BuoyantForceField.inl[>"]:#include <SofaBoundaryCondition/BuoyantForceField.inl>:
s:#include *[<"]sofa/component/forcefield/BuoyantForceField.h[>"]:#include <SofaBoundaryCondition/BuoyantForceField.h>:
s:#include *[<"]sofa/component/constraintset/LMConstraintDirectSolver.h[>"]:#include <SofaConstraint/LMConstraintDirectSolver.h>:
s:#include *[<"]sofa/component/constraintset/LMConstraintSolver.h[>"]:#include <SofaConstraint/LMConstraintSolver.h>:
s:#include *[<"]sofa/component/constraintset/DistanceLMConstraint.inl[>"]:#include <SofaConstraint/DistanceLMConstraint.inl>:
s:#include *[<"]sofa/component/constraintset/DistanceLMConstraint.h[>"]:#include <SofaConstraint/DistanceLMConstraint.h>:
s:#include *[<"]sofa/component/constraintset/DistanceLMContactConstraint.inl[>"]:#include <SofaConstraint/DistanceLMContactConstraint.inl>:
s:#include *[<"]sofa/component/constraintset/DistanceLMContactConstraint.h[>"]:#include <SofaConstraint/DistanceLMContactConstraint.h>:
s:#include *[<"]sofa/component/constraintset/FixedLMConstraint.inl[>"]:#include <SofaConstraint/FixedLMConstraint.inl>:
s:#include *[<"]sofa/component/constraintset/FixedLMConstraint.h[>"]:#include <SofaConstraint/FixedLMConstraint.h>:
s:#include *[<"]sofa/component/constraintset/DOFBlockerLMConstraint.inl[>"]:#include <SofaConstraint/DOFBlockerLMConstraint.inl>:
s:#include *[<"]sofa/component/constraintset/DOFBlockerLMConstraint.h[>"]:#include <SofaConstraint/DOFBlockerLMConstraint.h>:
s:#include *[<"]sofa/component/collision/BarycentricDistanceLMConstraintContact.inl[>"]:#include <SofaConstraint/BarycentricDistanceLMConstraintContact.inl>:
s:#include *[<"]sofa/component/collision/BarycentricDistanceLMConstraintContact.h[>"]:#include <SofaConstraint/BarycentricDistanceLMConstraintContact.h>:
s:#include *[<"]sofa/component/collision/ConstraintAttachBodyPerformer.inl[>"]:#include <SofaConstraint/ConstraintAttachBodyPerformer.inl>:
s:#include *[<"]sofa/component/collision/ConstraintAttachBodyPerformer.h[>"]:#include <SofaConstraint/ConstraintAttachBodyPerformer.h>:
s:#include *[<"]sofa/component/constraintset/SlidingConstraint.inl[>"]:#include <SofaConstraint/SlidingConstraint.inl>:
s:#include *[<"]sofa/component/constraintset/SlidingConstraint.h[>"]:#include <SofaConstraint/SlidingConstraint.h>:
s:#include *[<"]sofa/component/constraintset/StopperConstraint.inl[>"]:#include <SofaConstraint/StopperConstraint.inl>:
s:#include *[<"]sofa/component/constraintset/StopperConstraint.h[>"]:#include <SofaConstraint/StopperConstraint.h>:
s:#include *[<"]sofa/component/animationloop/ConstraintAnimationLoop.h[>"]:#include <SofaConstraint/ConstraintAnimationLoop.h>:
s:#include *[<"]sofa/component/constraintset/BilateralInteractionConstraint.inl[>"]:#include <SofaConstraint/BilateralInteractionConstraint.inl>:
s:#include *[<"]sofa/component/constraintset/BilateralInteractionConstraint.h[>"]:#include <SofaConstraint/BilateralInteractionConstraint.h>:
s:#include *[<"]sofa/component/constraintset/GenericConstraintSolver.h[>"]:#include <SofaConstraint/GenericConstraintSolver.h>:
s:#include *[<"]sofa/component/constraintset/ContactDescription.h[>"]:#include <SofaConstraint/ContactDescription.h>:
s:#include *[<"]sofa/component/animationloop/FreeMotionAnimationLoop.h[>"]:#include <SofaConstraint/FreeMotionAnimationLoop.h>:
s:#include *[<"]sofa/component/constraintset/ConstraintSolverImpl.h[>"]:#include <SofaConstraint/ConstraintSolverImpl.h>:
s:#include *[<"]sofa/component/constraintset/LCPConstraintSolver.h[>"]:#include <SofaConstraint/LCPConstraintSolver.h>:
s:#include *[<"]sofa/component/constraintset/GenericConstraintCorrection.inl[>"]:#include <SofaConstraint/GenericConstraintCorrection.inl>:
s:#include *[<"]sofa/component/constraintset/GenericConstraintCorrection.h[>"]:#include <SofaConstraint/GenericConstraintCorrection.h>:
s:#include *[<"]sofa/component/constraintset/LinearSolverConstraintCorrection.inl[>"]:#include <SofaConstraint/LinearSolverConstraintCorrection.inl>:
s:#include *[<"]sofa/component/constraintset/LinearSolverConstraintCorrection.h[>"]:#include <SofaConstraint/LinearSolverConstraintCorrection.h>:
s:#include *[<"]sofa/component/constraintset/PrecomputedConstraintCorrection.inl[>"]:#include <SofaConstraint/PrecomputedConstraintCorrection.inl>:
s:#include *[<"]sofa/component/constraintset/PrecomputedConstraintCorrection.h[>"]:#include <SofaConstraint/PrecomputedConstraintCorrection.h>:
s:#include *[<"]sofa/component/constraintset/UncoupledConstraintCorrection.inl[>"]:#include <SofaConstraint/UncoupledConstraintCorrection.inl>:
s:#include *[<"]sofa/component/constraintset/UncoupledConstraintCorrection.h[>"]:#include <SofaConstraint/UncoupledConstraintCorrection.h>:
s:#include *[<"]sofa/component/constraintset/UnilateralInteractionConstraint.inl[>"]:#include <SofaConstraint/UnilateralInteractionConstraint.inl>:
s:#include *[<"]sofa/component/constraintset/UnilateralInteractionConstraint.h[>"]:#include <SofaConstraint/UnilateralInteractionConstraint.h>:
s:#include *[<"]sofa/component/collision/StickContactConstraint.inl[>"]:#include <SofaConstraint/StickContactConstraint.inl>:
s:#include *[<"]sofa/component/collision/StickContactConstraint.h[>"]:#include <SofaConstraint/StickContactConstraint.h>:
s:#include *[<"]sofa/component/collision/FrictionContact.inl[>"]:#include <SofaConstraint/FrictionContact.inl>:
s:#include *[<"]sofa/component/collision/FrictionContact.h[>"]:#include <SofaConstraint/FrictionContact.h>:
s:#include *[<"]sofa/component/collision/LMDNewProximityIntersection.inl[>"]:#include <SofaConstraint/LMDNewProximityIntersection.inl>:
s:#include *[<"]sofa/component/collision/LMDNewProximityIntersection.h[>"]:#include <SofaConstraint/LMDNewProximityIntersection.h>:
s:#include *[<"]sofa/component/collision/LocalMinDistance.inl[>"]:#include <SofaConstraint/LocalMinDistance.inl>:
s:#include *[<"]sofa/component/collision/LocalMinDistance.h[>"]:#include <SofaConstraint/LocalMinDistance.h>:
s:#include *[<"]sofa/component/interactionforcefield/VectorSpringForceField.inl[>"]:#include <SofaDeformable/VectorSpringForceField.inl>:
s:#include *[<"]sofa/component/interactionforcefield/VectorSpringForceField.h[>"]:#include <SofaDeformable/VectorSpringForceField.h>:
s:#include *[<"]sofa/component/interactionforcefield/TriangleBendingSprings.inl[>"]:#include <SofaDeformable/TriangleBendingSprings.inl>:
s:#include *[<"]sofa/component/interactionforcefield/TriangleBendingSprings.h[>"]:#include <SofaDeformable/TriangleBendingSprings.h>:
s:#include *[<"]sofa/component/interactionforcefield/StiffSpringForceField.inl[>"]:#include <SofaDeformable/StiffSpringForceField.inl>:
s:#include *[<"]sofa/component/interactionforcefield/StiffSpringForceField.h[>"]:#include <SofaDeformable/StiffSpringForceField.h>:
s:#include *[<"]sofa/component/interactionforcefield/SpringForceField.inl[>"]:#include <SofaDeformable/SpringForceField.inl>:
s:#include *[<"]sofa/component/interactionforcefield/SpringForceField.h[>"]:#include <SofaDeformable/SpringForceField.h>:
s:#include *[<"]sofa/component/interactionforcefield/RegularGridSpringForceField.inl[>"]:#include <SofaDeformable/RegularGridSpringForceField.inl>:
s:#include *[<"]sofa/component/interactionforcefield/RegularGridSpringForceField.h[>"]:#include <SofaDeformable/RegularGridSpringForceField.h>:
s:#include *[<"]sofa/component/interactionforcefield/QuadBendingSprings.inl[>"]:#include <SofaDeformable/QuadBendingSprings.inl>:
s:#include *[<"]sofa/component/interactionforcefield/QuadBendingSprings.h[>"]:#include <SofaDeformable/QuadBendingSprings.h>:
s:#include *[<"]sofa/component/interactionforcefield/MeshSpringForceField.inl[>"]:#include <SofaDeformable/MeshSpringForceField.inl>:
s:#include *[<"]sofa/component/interactionforcefield/MeshSpringForceField.h[>"]:#include <SofaDeformable/MeshSpringForceField.h>:
s:#include *[<"]sofa/component/interactionforcefield/FrameSpringForceField.inl[>"]:#include <SofaDeformable/FrameSpringForceField.inl>:
s:#include *[<"]sofa/component/interactionforcefield/FrameSpringForceField.h[>"]:#include <SofaDeformable/FrameSpringForceField.h>:
s:#include *[<"]sofa/component/forcefield/TriangularTensorMassForceField.inl[>"]:#include <SofaDeformable/TriangularTensorMassForceField.inl>:
s:#include *[<"]sofa/component/forcefield/TriangularTensorMassForceField.h[>"]:#include <SofaDeformable/TriangularTensorMassForceField.h>:
s:#include *[<"]sofa/component/forcefield/TriangularQuadraticSpringsForceField.inl[>"]:#include <SofaDeformable/TriangularQuadraticSpringsForceField.inl>:
s:#include *[<"]sofa/component/forcefield/TriangularQuadraticSpringsForceField.h[>"]:#include <SofaDeformable/TriangularQuadraticSpringsForceField.h>:
s:#include *[<"]sofa/component/forcefield/TriangularBiquadraticSpringsForceField.inl[>"]:#include <SofaDeformable/TriangularBiquadraticSpringsForceField.inl>:
s:#include *[<"]sofa/component/forcefield/TriangularBiquadraticSpringsForceField.h[>"]:#include <SofaDeformable/TriangularBiquadraticSpringsForceField.h>:
s:#include *[<"]sofa/component/forcefield/TriangularBendingSprings.inl[>"]:#include <SofaDeformable/TriangularBendingSprings.inl>:
s:#include *[<"]sofa/component/forcefield/TriangularBendingSprings.h[>"]:#include <SofaDeformable/TriangularBendingSprings.h>:
s:#include *[<"]sofa/component/forcefield/RestShapeSpringsForceField.inl[>"]:#include <SofaDeformable/RestShapeSpringsForceField.inl>:
s:#include *[<"]sofa/component/forcefield/RestShapeSpringsForceField.h[>"]:#include <SofaDeformable/RestShapeSpringsForceField.h>:
s:#include *[<"]sofa/component/forcefield/QuadularBendingSprings.inl[>"]:#include <SofaDeformable/QuadularBendingSprings.inl>:
s:#include *[<"]sofa/component/forcefield/QuadularBendingSprings.h[>"]:#include <SofaDeformable/QuadularBendingSprings.h>:
s:#include *[<"]sofa/component/forcefield/FastTriangularBendingSprings.inl[>"]:#include <SofaDeformable/FastTriangularBendingSprings.inl>:
s:#include *[<"]sofa/component/forcefield/FastTriangularBendingSprings.h[>"]:#include <SofaDeformable/FastTriangularBendingSprings.h>:
s:#include *[<"]sofa/component/misc/InteractingBehaviorModel.h[>"]:#include <SofaGraphComponent/InteractingBehaviorModel.h>:
s:#include *[<"]sofa/component/misc/RequiredPlugin.h[>"]:#include <SofaGraphComponent/RequiredPlugin.h>:
s:#include *[<"]sofa/component/misc/PauseAnimationOnEvent.h[>"]:#include <SofaGraphComponent/PauseAnimationOnEvent.h>:
s:#include *[<"]sofa/component/misc/PauseAnimation.h[>"]:#include <SofaGraphComponent/PauseAnimation.h>:
s:#include *[<"]sofa/component/contextobject/Gravity.h[>"]:#include <SofaGraphComponent/Gravity.h>:
s:#include *[<"]sofa/component/configurationsetting/ViewerSetting.h[>"]:#include <SofaGraphComponent/ViewerSetting.h>:
s:#include *[<"]sofa/component/configurationsetting/StatsSetting.h[>"]:#include <SofaGraphComponent/StatsSetting.h>:
s:#include *[<"]sofa/component/configurationsetting/SofaDefaultPathSetting.h[>"]:#include <SofaGraphComponent/SofaDefaultPathSetting.h>:
s:#include *[<"]sofa/component/configurationsetting/MouseButtonSetting.h[>"]:#include <SofaGraphComponent/MouseButtonSetting.h>:
s:#include *[<"]sofa/component/configurationsetting/FixPickedParticleButtonSetting.h[>"]:#include <SofaGraphComponent/FixPickedParticleButtonSetting.h>:
s:#include *[<"]sofa/component/configurationsetting/BackgroundSetting.h[>"]:#include <SofaGraphComponent/BackgroundSetting.h>:
s:#include *[<"]sofa/component/configurationsetting/AttachBodyButtonSetting.h[>"]:#include <SofaGraphComponent/AttachBodyButtonSetting.h>:
s:#include *[<"]sofa/component/configurationsetting/AddRecordedCameraButtonSetting.h[>"]:#include <SofaGraphComponent/AddRecordedCameraButtonSetting.h>:
s:#include *[<"]sofa/component/configurationsetting/AddFrameButtonSetting.h[>"]:#include <SofaGraphComponent/AddFrameButtonSetting.h>:
s:#include *[<"]sofa/component/misc/ReadTopology.inl[>"]:#include <SofaLoader/ReadTopology.inl>:
s:#include *[<"]sofa/component/misc/ReadTopology.h[>"]:#include <SofaLoader/ReadTopology.h>:
s:#include *[<"]sofa/component/misc/ReadState.inl[>"]:#include <SofaLoader/ReadState.inl>:
s:#include *[<"]sofa/component/misc/ReadState.h[>"]:#include <SofaLoader/ReadState.h>:
s:#include *[<"]sofa/component/misc/InputEventReader.h[>"]:#include <SofaLoader/InputEventReader.h>:
s:#include *[<"]sofa/component/loader/VoxelGridLoader.h[>"]:#include <SofaLoader/VoxelGridLoader.h>:
s:#include *[<"]sofa/component/loader/SphereLoader.h[>"]:#include <SofaLoader/SphereLoader.h>:
s:#include *[<"]sofa/component/loader/OffSequenceLoader.h[>"]:#include <SofaLoader/OffSequenceLoader.h>:
s:#include *[<"]sofa/component/loader/MeshXspLoader.h[>"]:#include <SofaLoader/MeshXspLoader.h>:
s:#include *[<"]sofa/component/loader/MeshSTLLoader.h[>"]:#include <SofaLoader/MeshSTLLoader.h>:
s:#include *[<"]sofa/component/loader/MeshVTKLoader.h[>"]:#include <SofaLoader/MeshVTKLoader.h>:
s:#include *[<"]sofa/component/loader/MeshTrianLoader.h[>"]:#include <SofaLoader/MeshTrianLoader.h>:
s:#include *[<"]sofa/component/loader/MeshOffLoader.h[>"]:#include <SofaLoader/MeshOffLoader.h>:
s:#include *[<"]sofa/component/loader/GIDMeshLoader.h[>"]:#include <SofaLoader/GIDMeshLoader.h>:
s:#include *[<"]sofa/component/loader/MeshObjLoader.h[>"]:#include <SofaLoader/MeshObjLoader.h>:
s:#include *[<"]sofa/component/loader/MeshGmshLoader.h[>"]:#include <SofaLoader/MeshGmshLoader.h>:
s:#include *[<"]sofa/component/loader/StringMeshCreator.h[>"]:#include <SofaLoader/StringMeshCreator.h>:
s:#include *[<"]sofa/component/loader/GridMeshCreator.h[>"]:#include <SofaLoader/GridMeshCreator.h>:
s:#include *[<"]sofa/component/mapping/HexahedronCompositeFEMMapping.inl[>"]:#include <SofaNonUniformFem/HexahedronCompositeFEMMapping.inl>:
s:#include *[<"]sofa/component/mapping/HexahedronCompositeFEMMapping.h[>"]:#include <SofaNonUniformFem/HexahedronCompositeFEMMapping.h>:
s:#include *[<"]sofa/component/forcefield/HexahedronCompositeFEMForceFieldAndMass.inl[>"]:#include <SofaNonUniformFem/HexahedronCompositeFEMForceFieldAndMass.inl>:
s:#include *[<"]sofa/component/forcefield/HexahedronCompositeFEMForceFieldAndMass.h[>"]:#include <SofaNonUniformFem/HexahedronCompositeFEMForceFieldAndMass.h>:
s:#include *[<"]sofa/component/topology/SparseGridRamificationTopology.h[>"]:#include <SofaNonUniformFem/SparseGridRamificationTopology.h>:
s:#include *[<"]sofa/component/topology/SparseGridMultipleTopology.h[>"]:#include <SofaNonUniformFem/SparseGridMultipleTopology.h>:
s:#include *[<"]sofa/component/topology/MultilevelHexahedronSetTopologyContainer.h[>"]:#include <SofaNonUniformFem/MultilevelHexahedronSetTopologyContainer.h>:
s:#include *[<"]sofa/component/topology/DynamicSparseGridTopologyModifier.h[>"]:#include <SofaNonUniformFem/DynamicSparseGridTopologyModifier.h>:
s:#include *[<"]sofa/component/topology/DynamicSparseGridTopologyContainer.h[>"]:#include <SofaNonUniformFem/DynamicSparseGridTopologyContainer.h>:
s:#include *[<"]sofa/component/topology/DynamicSparseGridTopologyAlgorithms.inl[>"]:#include <SofaNonUniformFem/DynamicSparseGridTopologyAlgorithms.inl>:
s:#include *[<"]sofa/component/topology/DynamicSparseGridTopologyAlgorithms.h[>"]:#include <SofaNonUniformFem/DynamicSparseGridTopologyAlgorithms.h>:
s:#include *[<"]sofa/component/topology/DynamicSparseGridGeometryAlgorithms.inl[>"]:#include <SofaNonUniformFem/DynamicSparseGridGeometryAlgorithms.inl>:
s:#include *[<"]sofa/component/topology/DynamicSparseGridGeometryAlgorithms.h[>"]:#include <SofaNonUniformFem/DynamicSparseGridGeometryAlgorithms.h>:
s:#include *[<"]sofa/component/forcefield/NonUniformHexahedronFEMForceFieldDensity.inl[>"]:#include <SofaNonUniformFem/NonUniformHexahedronFEMForceFieldDensity.inl>:
s:#include *[<"]sofa/component/forcefield/NonUniformHexahedronFEMForceFieldDensity.h[>"]:#include <SofaNonUniformFem/NonUniformHexahedronFEMForceFieldDensity.h>:
s:#include *[<"]sofa/component/forcefield/NonUniformHexahedronFEMForceFieldAndMass.inl[>"]:#include <SofaNonUniformFem/NonUniformHexahedronFEMForceFieldAndMass.inl>:
s:#include *[<"]sofa/component/forcefield/NonUniformHexahedronFEMForceFieldAndMass.h[>"]:#include <SofaNonUniformFem/NonUniformHexahedronFEMForceFieldAndMass.h>:
s:#include *[<"]sofa/component/forcefield/NonUniformHexahedralFEMForceFieldAndMass.inl[>"]:#include <SofaNonUniformFem/NonUniformHexahedralFEMForceFieldAndMass.inl>:
s:#include *[<"]sofa/component/forcefield/NonUniformHexahedralFEMForceFieldAndMass.h[>"]:#include <SofaNonUniformFem/NonUniformHexahedralFEMForceFieldAndMass.h>:
s:#include *[<"]sofa/component/container/LengthContainer.h[>"]:#include <SofaSimpleFem/LengthContainer.h>:
s:#include *[<"]sofa/component/container/RadiusContainer.h[>"]:#include <SofaSimpleFem/RadiusContainer.h>:
s:#include *[<"]sofa/component/container/StiffnessContainer.h[>"]:#include <SofaSimpleFem/StiffnessContainer.h>:
s:#include *[<"]sofa/component/container/PoissonContainer.h[>"]:#include <SofaSimpleFem/PoissonContainer.h>:
s:#include *[<"]sofa/component/forcefield/TriangularFEMForceFieldOptim.inl[>"]:#include <SofaSimpleFem/TriangularFEMForceFieldOptim.inl>:
s:#include *[<"]sofa/component/forcefield/TriangularFEMForceFieldOptim.h[>"]:#include <SofaSimpleFem/TriangularFEMForceFieldOptim.h>:
s:#include *[<"]sofa/component/forcefield/TriangularFEMForceField.inl[>"]:#include <SofaSimpleFem/TriangularFEMForceField.inl>:
s:#include *[<"]sofa/component/forcefield/TriangularFEMForceField.h[>"]:#include <SofaSimpleFem/TriangularFEMForceField.h>:
s:#include *[<"]sofa/component/forcefield/TriangleFEMForceField.inl[>"]:#include <SofaSimpleFem/TriangleFEMForceField.inl>:
s:#include *[<"]sofa/component/forcefield/TriangleFEMForceField.h[>"]:#include <SofaSimpleFem/TriangleFEMForceField.h>:
s:#include *[<"]sofa/component/forcefield/TriangularAnisotropicFEMForceField.inl[>"]:#include <SofaSimpleFem/TriangularAnisotropicFEMForceField.inl>:
s:#include *[<"]sofa/component/forcefield/TriangularAnisotropicFEMForceField.h[>"]:#include <SofaSimpleFem/TriangularAnisotropicFEMForceField.h>:
s:#include *[<"]sofa/component/forcefield/TetrahedronFEMForceField.inl[>"]:#include <SofaSimpleFem/TetrahedronFEMForceField.inl>:
s:#include *[<"]sofa/component/forcefield/TetrahedronFEMForceField.h[>"]:#include <SofaSimpleFem/TetrahedronFEMForceField.h>:
s:#include *[<"]sofa/component/forcefield/TetrahedralCorotationalFEMForceField.inl[>"]:#include <SofaSimpleFem/TetrahedralCorotationalFEMForceField.inl>:
s:#include *[<"]sofa/component/forcefield/TetrahedralCorotationalFEMForceField.h[>"]:#include <SofaSimpleFem/TetrahedralCorotationalFEMForceField.h>:
s:#include *[<"]sofa/component/forcefield/HexahedronFEMForceFieldAndMass.inl[>"]:#include <SofaSimpleFem/HexahedronFEMForceFieldAndMass.inl>:
s:#include *[<"]sofa/component/forcefield/HexahedronFEMForceFieldAndMass.h[>"]:#include <SofaSimpleFem/HexahedronFEMForceFieldAndMass.h>:
s:#include *[<"]sofa/component/forcefield/HexahedronFEMForceField.inl[>"]:#include <SofaSimpleFem/HexahedronFEMForceField.inl>:
s:#include *[<"]sofa/component/forcefield/HexahedronFEMForceField.h[>"]:#include <SofaSimpleFem/HexahedronFEMForceField.h>:
s:#include *[<"]sofa/component/forcefield/HexahedralFEMForceFieldAndMass.inl[>"]:#include <SofaSimpleFem/HexahedralFEMForceFieldAndMass.inl>:
s:#include *[<"]sofa/component/forcefield/HexahedralFEMForceFieldAndMass.h[>"]:#include <SofaSimpleFem/HexahedralFEMForceFieldAndMass.h>:
s:#include *[<"]sofa/component/forcefield/HexahedralFEMForceField.inl[>"]:#include <SofaSimpleFem/HexahedralFEMForceField.inl>:
s:#include *[<"]sofa/component/forcefield/HexahedralFEMForceField.h[>"]:#include <SofaSimpleFem/HexahedralFEMForceField.h>:
s:#include *[<"]sofa/component/forcefield/BeamFEMForceField.inl[>"]:#include <SofaSimpleFem/BeamFEMForceField.inl>:
s:#include *[<"]sofa/component/forcefield/BeamFEMForceField.h[>"]:#include <SofaSimpleFem/BeamFEMForceField.h>:
s:#include *[<"]sofa/component/topology/SubsetTopologicalMapping.h[>"]:#include <SofaTopologyMapping/SubsetTopologicalMapping.h>:
s:#include *[<"]sofa/component/topology/IdentityTopologicalMapping.h[>"]:#include <SofaTopologyMapping/IdentityTopologicalMapping.h>:
s:#include *[<"]sofa/component/topology/Triangle2EdgeTopologicalMapping.h[>"]:#include <SofaTopologyMapping/Triangle2EdgeTopologicalMapping.h>:
s:#include *[<"]sofa/component/topology/Tetra2TriangleTopologicalMapping.h[>"]:#include <SofaTopologyMapping/Tetra2TriangleTopologicalMapping.h>:
s:#include *[<"]sofa/component/topology/SimpleTesselatedTetraTopologicalMapping.h[>"]:#include <SofaTopologyMapping/SimpleTesselatedTetraTopologicalMapping.h>:
s:#include *[<"]sofa/component/topology/SimpleTesselatedHexaTopologicalMapping.h[>"]:#include <SofaTopologyMapping/SimpleTesselatedHexaTopologicalMapping.h>:
s:#include *[<"]sofa/component/topology/Quad2TriangleTopologicalMapping.h[>"]:#include <SofaTopologyMapping/Quad2TriangleTopologicalMapping.h>:
s:#include *[<"]sofa/component/topology/Mesh2BezierTopologicalMapping.h[>"]:#include <SofaTopologyMapping/Mesh2BezierTopologicalMapping.h>:
s:#include *[<"]sofa/component/topology/Mesh2PointTopologicalMapping.h[>"]:#include <SofaTopologyMapping/Mesh2PointTopologicalMapping.h>:
s:#include *[<"]sofa/component/topology/Hexa2TetraTopologicalMapping.h[>"]:#include <SofaTopologyMapping/Hexa2TetraTopologicalMapping.h>:
s:#include *[<"]sofa/component/topology/Hexa2QuadTopologicalMapping.h[>"]:#include <SofaTopologyMapping/Hexa2QuadTopologicalMapping.h>:
s:#include *[<"]sofa/component/topology/Edge2QuadTopologicalMapping.h[>"]:#include <SofaTopologyMapping/Edge2QuadTopologicalMapping.h>:
s:#include *[<"]sofa/component/topology/CenterPointTopologicalMapping.h[>"]:#include <SofaTopologyMapping/CenterPointTopologicalMapping.h>:
s:#include *[<"]sofa/component/mapping/SimpleTesselatedTetraMechanicalMapping.inl[>"]:#include <SofaTopologyMapping/SimpleTesselatedTetraMechanicalMapping.inl>:
s:#include *[<"]sofa/component/mapping/SimpleTesselatedTetraMechanicalMapping.h[>"]:#include <SofaTopologyMapping/SimpleTesselatedTetraMechanicalMapping.h>:
s:#include *[<"]sofa/component/mapping/Mesh2PointMechanicalMapping.inl[>"]:#include <SofaTopologyMapping/Mesh2PointMechanicalMapping.inl>:
s:#include *[<"]sofa/component/mapping/Mesh2PointMechanicalMapping.h[>"]:#include <SofaTopologyMapping/Mesh2PointMechanicalMapping.h>:
s:#include *[<"]sofa/component/controller/InterpolationController.inl[>"]:#include <SofaUserInteraction/InterpolationController.inl>:
s:#include *[<"]sofa/component/controller/InterpolationController.h[>"]:#include <SofaUserInteraction/InterpolationController.h>:
s:#include *[<"]sofa/component/controller/NodeToggleController.h[>"]:#include <SofaUserInteraction/NodeToggleController.h>:
s:#include *[<"]sofa/component/controller/MechanicalStateControllerOmni.inl[>"]:#include <SofaUserInteraction/MechanicalStateControllerOmni.inl>:
s:#include *[<"]sofa/component/controller/MechanicalStateControllerOmni.h[>"]:#include <SofaUserInteraction/MechanicalStateControllerOmni.h>:
s:#include *[<"]sofa/component/collision/StartNavigationPerformer.h[>"]:#include <SofaUserInteraction/StartNavigationPerformer.h>:
s:#include *[<"]sofa/component/collision/AddRecordedCameraPerformer.h[>"]:#include <SofaUserInteraction/AddRecordedCameraPerformer.h>:
s:#include *[<"]sofa/component/collision/AddFramePerformer.inl[>"]:#include <SofaUserInteraction/AddFramePerformer.inl>:
s:#include *[<"]sofa/component/collision/AddFramePerformer.h[>"]:#include <SofaUserInteraction/AddFramePerformer.h>:
s:#include *[<"]sofa/component/collision/CuttingPoint.h[>"]:#include <SofaUserInteraction/CuttingPoint.h>:
s:#include *[<"]sofa/component/collision/TopologicalChangeManager.h[>"]:#include <SofaUserInteraction/TopologicalChangeManager.h>:
s:#include *[<"]sofa/component/collision/InciseAlongPathPerformer.h[>"]:#include <SofaUserInteraction/InciseAlongPathPerformer.h>:
s:#include *[<"]sofa/component/collision/RemovePrimitivePerformer.inl[>"]:#include <SofaUserInteraction/RemovePrimitivePerformer.inl>:
s:#include *[<"]sofa/component/collision/RemovePrimitivePerformer.h[>"]:#include <SofaUserInteraction/RemovePrimitivePerformer.h>:
s:#include *[<"]sofa/component/collision/RayNewProximityIntersection.h[>"]:#include <SofaUserInteraction/RayNewProximityIntersection.h>:
s:#include *[<"]sofa/component/collision/RayDiscreteIntersection.inl[>"]:#include <SofaUserInteraction/RayDiscreteIntersection.inl>:
s:#include *[<"]sofa/component/collision/RayDiscreteIntersection.h[>"]:#include <SofaUserInteraction/RayDiscreteIntersection.h>:
s:#include *[<"]sofa/component/collision/RayModel.h[>"]:#include <SofaUserInteraction/RayModel.h>:
s:#include *[<"]sofa/component/collision/Ray.h[>"]:#include <SofaUserInteraction/Ray.h>:
s:#include *[<"]sofa/component/controller/MechanicalStateController.inl[>"]:#include <SofaUserInteraction/MechanicalStateController.inl>:
s:#include *[<"]sofa/component/controller/MechanicalStateController.h[>"]:#include <SofaUserInteraction/MechanicalStateController.h>:
s:#include *[<"]sofa/component/controller/EdgeSetController.inl[>"]:#include <SofaUserInteraction/EdgeSetController.inl>:
s:#include *[<"]sofa/component/controller/EdgeSetController.h[>"]:#include <SofaUserInteraction/EdgeSetController.h>:
s:#include *[<"]sofa/component/controller/Controller.h[>"]:#include <SofaUserInteraction/Controller.h>:
s:#include *[<"]sofa/component/controller/ArticulatedHierarchyBVHController.h[>"]:#include <SofaUserInteraction/ArticulatedHierarchyBVHController.h>:
s:#include *[<"]sofa/component/controller/ArticulatedHierarchyController.h[>"]:#include <SofaUserInteraction/ArticulatedHierarchyController.h>:
s:#include *[<"]sofa/component/collision/GraspingManager.h[>"]:#include <SofaUserInteraction/GraspingManager.h>:
s:#include *[<"]sofa/component/collision/SuturePointPerformer.inl[>"]:#include <SofaUserInteraction/SuturePointPerformer.inl>:
s:#include *[<"]sofa/component/collision/SuturePointPerformer.h[>"]:#include <SofaUserInteraction/SuturePointPerformer.h>:
s:#include *[<"]sofa/component/collision/InteractionPerformer.h[>"]:#include <SofaUserInteraction/InteractionPerformer.h>:
s:#include *[<"]sofa/component/collision/FixParticlePerformer.inl[>"]:#include <SofaUserInteraction/FixParticlePerformer.inl>:
s:#include *[<"]sofa/component/collision/FixParticlePerformer.h[>"]:#include <SofaUserInteraction/FixParticlePerformer.h>:
s:#include *[<"]sofa/component/collision/AttachBodyPerformer.inl[>"]:#include <SofaUserInteraction/AttachBodyPerformer.inl>:
s:#include *[<"]sofa/component/collision/AttachBodyPerformer.h[>"]:#include <SofaUserInteraction/AttachBodyPerformer.h>:
s:#include *[<"]sofa/component/collision/MouseInteractor.inl[>"]:#include <SofaUserInteraction/MouseInteractor.inl>:
s:#include *[<"]sofa/component/collision/MouseInteractor.h[>"]:#include <SofaUserInteraction/MouseInteractor.h>:
s:#include *[<"]sofa/component/collision/ComponentMouseInteraction.inl[>"]:#include <SofaUserInteraction/ComponentMouseInteraction.inl>:
s:#include *[<"]sofa/component/collision/ComponentMouseInteraction.h[>"]:#include <SofaUserInteraction/ComponentMouseInteraction.h>:
s:#include *[<"]sofa/component/collision/DisabledContact.h[>"]:#include <SofaUserInteraction/DisabledContact.h>:
s:#include *[<"]sofa/component/collision/RayContact.h[>"]:#include <SofaUserInteraction/RayContact.h>:
s:#include *[<"]sofa/component/collision/RayTraceDetection.h[>"]:#include <SofaUserInteraction/RayTraceDetection.h>:
s:#include *[<"]sofa/component/collision/FFDDistanceGridDiscreteIntersection.inl[>"]:#include <SofaVolumetricData/FFDDistanceGridDiscreteIntersection.inl>:
s:#include *[<"]sofa/component/collision/FFDDistanceGridDiscreteIntersection.h[>"]:#include <SofaVolumetricData/FFDDistanceGridDiscreteIntersection.h>:
s:#include *[<"]sofa/component/collision/RigidDistanceGridDiscreteIntersection.inl[>"]:#include <SofaVolumetricData/RigidDistanceGridDiscreteIntersection.inl>:
s:#include *[<"]sofa/component/collision/RigidDistanceGridDiscreteIntersection.h[>"]:#include <SofaVolumetricData/RigidDistanceGridDiscreteIntersection.h>:
s:#include *[<"]sofa/component/collision/DistanceGridCollisionModel.h[>"]:#include <SofaVolumetricData/DistanceGridCollisionModel.h>:
s:#include *[<"]sofa/component/container/DistanceGrid.h[>"]:#include <SofaVolumetricData/DistanceGrid.h>:
s:#include *[<"]sofa/component/mapping/ImplicitSurfaceMapping.inl[>"]:#include <SofaVolumetricData/ImplicitSurfaceMapping.inl>:
s:#include *[<"]sofa/component/mapping/ImplicitSurfaceMapping.h[>"]:#include <SofaVolumetricData/ImplicitSurfaceMapping.h>:
s:#include *[<"]sofa/component/forcefield/DistanceGridForceField.inl[>"]:#include <SofaVolumetricData/DistanceGridForceField.inl>:
s:#include *[<"]sofa/component/forcefield/DistanceGridForceField.h[>"]:#include <SofaVolumetricData/DistanceGridForceField.h>:
s:#include *[<"]sofa/component/container/InterpolatedImplicitSurface.inl[>"]:#include <SofaVolumetricData/InterpolatedImplicitSurface.inl>:
s:#include *[<"]sofa/component/container/InterpolatedImplicitSurface.h[>"]:#include <SofaVolumetricData/InterpolatedImplicitSurface.h>:
s:#include *[<"]sofa/component/container/ImplicitSurfaceContainer.h[>"]:#include <SofaVolumetricData/ImplicitSurfaceContainer.h>:
s:#include *[<"]sofa/component/BaseAnimationLoop.h[>"]:#include <SofaBaseAnimationLoop/BaseAnimationLoop.h>:
s:#include *[<"]sofa/component/BaseCollision.h[>"]:#include <SofaBaseCollision/BaseCollision.h>:
s:#include *[<"]sofa/component/BaseLinearSolver.h[>"]:#include <SofaBaseLinearSolver/BaseLinearSolver.h>:
s:#include *[<"]sofa/component/BaseMechanics.h[>"]:#include <SofaBaseMechanics/BaseMechanics.h>:
s:#include *[<"]sofa/component/BaseTopology.h[>"]:#include <SofaBaseTopology/BaseTopology.h>:
s:#include *[<"]sofa/component/BaseVisual.h[>"]:#include <SofaBaseVisual/BaseVisual.h>:
s:#include *[<"]sofa/component/BoundaryCondition.h[>"]:#include <SofaBoundaryCondition/BoundaryCondition.h>:
s:#include *[<"]sofa/component/ComponentAdvanced.h[>"]:#include <SofaComponentAdvanced/ComponentAdvanced.h>:
s:#include *[<"]sofa/component/ComponentBase.h[>"]:#include <SofaComponentBase/ComponentBase.h>:
s:#include *[<"]sofa/component/ComponentCommon.h[>"]:#include <SofaComponentCommon/ComponentCommon.h>:
s:#include *[<"]sofa/component/ComponentGeneral.h[>"]:#include <SofaComponentGeneral/ComponentGeneral.h>:
s:#include *[<"]sofa/component/ComponentMain.h[>"]:#include <SofaComponentMain/ComponentMain.h>:
s:#include *[<"]sofa/component/ComponentMisc.h[>"]:#include <SofaComponentMisc/ComponentMisc.h>:
s:#include *[<"]sofa/component/Constraint.h[>"]:#include <SofaConstraint/Constraint.h>:
s:#include *[<"]sofa/component/Deformable.h[>"]:#include <SofaDeformable/Deformable.h>:
s:#include *[<"]sofa/component/DenseSolver.h[>"]:#include <SofaDenseSolver/DenseSolver.h>:
s:#include *[<"]sofa/component/Eigen2Solver.h[>"]:#include <SofaEigen2Solver/Eigen2Solver.h>:
s:#include *[<"]sofa/component/Engine.h[>"]:#include <SofaEngine/Engine.h>:
s:#include *[<"]sofa/component/EulerianFluid.h[>"]:#include <SofaEulerianFluid/EulerianFluid.h>:
s:#include *[<"]sofa/component/ExplicitOdeSolver.h[>"]:#include <SofaExplicitOdeSolver/ExplicitOdeSolver.h>:
s:#include *[<"]sofa/component/Exporter.h[>"]:#include <SofaExporter/Exporter.h>:
s:#include *[<"]sofa/component/GraphComponent.h[>"]:#include <SofaGraphComponent/GraphComponent.h>:
s:#include *[<"]sofa/component/Haptics.h[>"]:#include <SofaHaptics/Haptics.h>:
s:#include *[<"]sofa/component/ImplicitOdeSolver.h[>"]:#include <SofaImplicitOdeSolver/ImplicitOdeSolver.h>:
s:#include *[<"]sofa/component/Loader.h[>"]:#include <SofaLoader/Loader.h>:
s:#include *[<"]sofa/component/MeshCollision.h[>"]:#include <SofaMeshCollision/MeshCollision.h>:
s:#include *[<"]sofa/component/Misc.h[>"]:#include <SofaMisc/Misc.h>:
s:#include *[<"]sofa/component/MiscCollision.h[>"]:#include <SofaMiscCollision/MiscCollision.h>:
s:#include *[<"]sofa/component/MiscEngine.h[>"]:#include <SofaMiscEngine/MiscEngine.h>:
s:#include *[<"]sofa/component/MiscFem.h[>"]:#include <SofaMiscFem/MiscFem.h>:
s:#include *[<"]sofa/component/MiscForceField.h[>"]:#include <SofaMiscForceField/MiscForceField.h>:
s:#include *[<"]sofa/component/MiscMapping.h[>"]:#include <SofaMiscMapping/MiscMapping.h>:
s:#include *[<"]sofa/component/MiscSolver.h[>"]:#include <SofaMiscSolver/MiscSolver.h>:
s:#include *[<"]sofa/component/MiscTopology.h[>"]:#include <SofaMiscTopology/MiscTopology.h>:
s:#include *[<"]sofa/component/NonUniformFem.h[>"]:#include <SofaNonUniformFem/NonUniformFem.h>:
s:#include *[<"]sofa/component/ObjectInteraction.h[>"]:#include <SofaObjectInteraction/ObjectInteraction.h>:
s:#include *[<"]sofa/component/OpenglVisual.h[>"]:#include <SofaOpenglVisual/OpenglVisual.h>:
s:#include *[<"]sofa/component/PardisoSolver.h[>"]:#include <SofaPardisoSolver/PardisoSolver.h>:
s:#include *[<"]sofa/component/Preconditioner.h[>"]:#include <SofaPreconditioner/Preconditioner.h>:
s:#include *[<"]sofa/component/Rigid.h[>"]:#include <SofaRigid/Rigid.h>:
s:#include *[<"]sofa/component/SimpleFem.h[>"]:#include <SofaSimpleFem/SimpleFem.h>:
s:#include *[<"]sofa/component/SparseSolver.h[>"]:#include <SofaSparseSolver/SparseSolver.h>:
s:#include *[<"]sofa/component/SphFluid.h[>"]:#include <SofaSphFluid/SphFluid.h>:
s:#include *[<"]sofa/component/TaucsSolver.h[>"]:#include <SofaTaucsSolver/TaucsSolver.h>:
s:#include *[<"]sofa/component/TopologyMapping.h[>"]:#include <SofaTopologyMapping/TopologyMapping.h>:
s:#include *[<"]sofa/component/UserInteraction.h[>"]:#include <SofaUserInteraction/UserInteraction.h>:
s:#include *[<"]sofa/component/Validation.h[>"]:#include <SofaValidation/Validation.h>:
s:#include *[<"]sofa/component/VolumetricData.h[>"]:#include <SofaVolumetricData/VolumetricData.h>:
s:#include *[<"]sofa/component/engine/TransformMatrixEngine.h[>"]:#include <SofaEngine/TransformMatrixEngine.h>:
s:#include *[<"]sofa/component/engine/GenerateCylinder.h[>"]:#include <SofaEngine/GenerateCylinder.h>:
s:#include *[<"]sofa/component/forcefield/QuadPressureForceField.h[>"]:#include <SofaBoundaryCondition/QuadPressureForceField.h>:
s:#include *[<"]sofa/component/projectiveconstraintset/PatchTestMovementConstraint.h[>"]:#include <SofaBoundaryCondition/PatchTestMovementConstraint.h>:
s:#include *[<"]sofa/component/collision/CylinderModel.h[>"]:#include <SofaBaseCollision/CylinderModel.h>:
s:#include *[<"]sofa/component/init.h[>"]:#include <SofaComponentMain/init.h>:
s:#include *[<"]sofa/component/misc/BlenderExporter.h[>"]:#include <SofaExporter/BlenderExporter.h>:
s:#include *[<"]sofa/component/misc/BlenderExporter.inl[>"]:#include <SofaExporter/BlenderExporter.inl>:
s:#include *[<"]sofa/component/engine/NormEngine.h[>"]:#include <SofaEngine/NormEngine.h>:
s:#include *[<"]sofa/component/engine/NormEngine.inl[>"]:#include <SofaEngine/NormEngine.inl>:
s:#include *[<"]sofa/component/forcefield/PREquivalentStiffnessForceField.h[>"]:#include <SofaMiscForceField/PREquivalentStiffnessForceField.h>:
s:#include *[<"]sofa/component/forcefield/PREquivalentStiffnessForceField.inl[>"]:#include <SofaMiscForceField/PREquivalentStiffnessForceField.inl>:
s:#include *[<"]sofa/component/interactionforcefield/PartialRigidificationForceField.h[>"]:#include <SofaObjectInteraction/PartialRigidificationForceField.h>:
s:#include *[<"]sofa/component/interactionforcefield/PartialRigidificationForceField.inl[>"]:#include <SofaObjectInteraction/PartialRigidificationForceField.inl>:
s:#include *[<"]sofa/component/engine/TestEngine.h[>"]:#include <SofaEngine/TestEngine.h>:
