#ifndef BINDING_IMAGEDATA_H
#define BINDING_IMAGEDATA_H

#include <SofaPython/PythonMacros.h>
#include "../ImageTypes.h"

SP_DECLARE_CLASS_TYPE(ImageCData)
SP_DECLARE_CLASS_TYPE(ImageUCData)
SP_DECLARE_CLASS_TYPE(ImageIData)
SP_DECLARE_CLASS_TYPE(ImageUIData)
SP_DECLARE_CLASS_TYPE(ImageSData)
SP_DECLARE_CLASS_TYPE(ImageUSData)
SP_DECLARE_CLASS_TYPE(ImageLData)
SP_DECLARE_CLASS_TYPE(ImageULData)
SP_DECLARE_CLASS_TYPE(ImageFData)
SP_DECLARE_CLASS_TYPE(ImageDData)
SP_DECLARE_CLASS_TYPE(ImageBData)


#endif

