#ifndef SOFA_BUILD_FILEMANAGER_SOFAPML_H
#define SOFA_BUILD_FILEMANAGER_SOFAPML_H

#include <sofa/helper/system/config.h>

#ifdef SOFA_BUILD_FILEMANAGER_PML
#  define SOFA_BUILD_FILEMANAGER_PML_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define SOFA_BUILD_FILEMANAGER_PML_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif

#endif
