#ifndef BINDING_TRIANGLESETTOPOLOGYMODIFIER_H
#define BINDING_TRIANGLESETTOPOLOGYMODIFIER_H

#include "PythonMacros.h"

SP_DECLARE_CLASS_TYPE(TriangleSetTopologyModifier)

#endif // BINDING_TRIANGLESETTOPOLOGYMODIFIER_H