/* Generated by Cython 0.28.3 */

#ifndef __PYX_HAVE__Binding_DataArray
#define __PYX_HAVE__Binding_DataArray


#ifndef __PYX_HAVE_API__Binding_DataArray

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *makeTypedArray(void);
__PYX_EXTERN_C PyObject *Data_toList(PyObject *);
__PYX_EXTERN_C bool Data_ass_subscript(PyObject *, PyObject *, PyObject *);

#endif /* !__PYX_HAVE_API__Binding_DataArray */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initBinding_DataArray(void);
#else
PyMODINIT_FUNC PyInit_Binding_DataArray(void);
#endif

#endif /* !__PYX_HAVE__Binding_DataArray */
