#ifndef BINDING_POINTSETTOPOLOGYMODIFIER_H
#define BINDING_POINTSETTOPOLOGYMODIFIER_H

#include "PythonMacros.h"

SP_DECLARE_CLASS_TYPE(PointSetTopologyModifier)

#endif // BINDING_POINTSETTOPOLOGYMODIFIER_H