#OFF
setSofaOption(SOFA-APPLICATION_GENERATERIGID OFF)
setSofaOption(SOFA-APPLICATION_MODELER OFF)
setSofaOption(SOFA-TUTORIAL_COMPOSITE_OBJECT OFF)
setSofaOption(SOFA-TUTORIAL_MIXED_PENDULUM OFF)
setSofaOption(SOFA-TUTORIAL_ONE_PARTICLE OFF)
setSofaOption(SOFA-TUTORIAL_ONE_TETRAHEDRON OFF)
