cmake_minimum_required(VERSION 2.8)

set(SOFA_FEATURES_DIR "${CMAKE_CURRENT_LIST_DIR}")
get_filename_component(SOFA_DIR ${SOFA_FEATURES_DIR} PATH)
set(SOFA_BIN_DIR "${SOFA_DIR}/bin")
set(SOFA_INC_DIR "${SOFA_DIR}/include")
set(SOFA_LIB_DIR "${SOFA_DIR}/lib")
set(SOFA_EXTLIBS_DIR "${SOFA_DIR}/extlibs")
set(SOFA_SHARE_DIR "${SOFA_DIR}/share")
set(SOFA_APPLICATIONS_DIR "${SOFA_DIR}/applications")
set(SOFA_APPLICATIONS_DEV_DIR "${SOFA_DIR}/applications-dev")
set(SOFA_FRAMEWORK_DIR "${SOFA_DIR}/framework")
set(SOFA_MODULES_DIR "${SOFA_DIR}/modules")

if(CMAKE_HOST_WIN32)
	set(SOFA_LIB_OS_DIR "${SOFA_LIB_DIR}/win32/Common")
elseif(CMAKE_HOST_APPLE)
	set(SOFA_LIB_OS_DIR "${SOFA_LIB_DIR}/macx")
endif()
