cmake_minimum_required(VERSION 2.8)

# group files
macro(groupFiles files regexFilter group)
	foreach(currentFile ${${files}})
		string(REGEX MATCH ${regexFilter} filteredFile ${currentFile})
		if(NOT filteredFile STREQUAL "")
			set(folder ${filteredFile})
			get_filename_component(filename ${folder} NAME)
			string(REPLACE ${filename} "" folder ${folder})
			if(NOT folder STREQUAL "")
				string(REGEX REPLACE "/+$" "" baseFolder ${folder})
				string(REPLACE "/" "\\" baseFolder ${baseFolder})
				source_group("${group}\\${baseFolder}" FILES ${filteredFile})
			endif()
		endif()
	endforeach()
endmacro()

# gather files
macro(GATHER_PROJECT_FILES files directories filter group)
	foreach(currentDirectory ${${directories}})
		file(GLOB pathes "${currentDirectory}/${filter}")
		foreach(currentPath ${pathes})
			file(RELATIVE_PATH currentFile "${CMAKE_CURRENT_BINARY_DIR}" "${currentPath}")
			list(APPEND ${files} "${currentFile}")
			source_group("${${group}}${currentDirectory}" FILES ${currentFile})
		endforeach()
	endforeach()
endmacro()