if(PRECONFIGURE_DONE)

	# print report
	unset(FINAL_LOG)
	if(GLOBAL_ERROR_MESSAGE)
		set(FINAL_LOG "${FINAL_LOG}Error(s):\n")
		foreach(ERROR_MESSAGE ${GLOBAL_ERROR_MESSAGE})
			set(FINAL_LOG "${FINAL_LOG}${ERROR_MESSAGE}\n")
		endforeach()
	endif()
	if(GLOBAL_WARNING_MESSAGE)
		set(FINAL_LOG "${FINAL_LOG}Warning(s):\n")
		foreach(WARNING_MESSAGE ${GLOBAL_WARNING_MESSAGE})
			set(FINAL_LOG "${FINAL_LOG}${WARNING_MESSAGE}\n")
		endforeach()
	endif()
	if(GLOBAL_LOG_MESSAGE)
		set(FINAL_LOG "${FINAL_LOG}Log(s):\n")
		foreach(LOG_MESSAGE ${GLOBAL_LOG_MESSAGE})
			set(FINAL_LOG "${FINAL_LOG}${LOG_MESSAGE}\n")
		endforeach()
	endif()
	if(GLOBAL_FORCE_RECONFIGURE)
		set(FINAL_LOG "${FINAL_LOG}###########################################################\nConfiguration changed, you must configure the project again\n###########################################################")
	endif()
	if(FINAL_LOG)
		set(FINAL_LOG "\nFinal report:\n${FINAL_LOG}\n\n")
		if(GLOBAL_ERROR_MESSAGE OR GLOBAL_FORCE_RECONFIGURE)
			message(SEND_ERROR "${FINAL_LOG}")
		elseif(GLOBAL_WARNING_MESSAGE)
			message(WARNING "${FINAL_LOG}")
		else()
			message(STATUS "${FINAL_LOG}")
		endif()
	endif()
	
endif()

set(PRECONFIGURE_DONE 1 CACHE INTERNAL "Configure does not set projects up, it just displays options")
