include(${CMAKE_CURRENT_LIST_DIR}/environment.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/functions.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/options.cmake)

if(PRECONFIGURE_DONE)
    include(${CMAKE_CURRENT_LIST_DIR}/externals.cmake)
    include(${CMAKE_CURRENT_LIST_DIR}/buildFlags.cmake)
else()
    message("")
    message(">>> SOFA framework pre-configuration complete")
    message(">>> Select your options and launch 'configure' or re-run cmake")
    message("")
endif()
