#ifndef INITPLUGINEXAMPLE_H
#define INITPLUGINEXAMPLE_H


#include <sofa/helper/system/config.h>

#ifdef SOFA_BUILD_PLUGINEXAMPLE
#define SOFA_PLUGINEXAMPLE_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#define SOFA_PLUGINEXAMPLE_API  SOFA_IMPORT_DYNAMIC_LIBRARY
#endif

#endif // INITPLUGINEXAMPLE_H
