# #####################################################################
# Automatically generated by qmake (2.01a) ven. 9. mai 13:25:52 2014
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += C:/Users/harid.TUMULTE/Documents/libQGL/cubeQGL/. \
    .
QT += opengl

# Input
SOURCES += main.cpp \
    myGLWidget.cpp \
    myWindow.cpp
HEADERS += myGLWidget.h \
    myWindow.h
