name: Launch performance testing
on:
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'sofa-framework' }}

    steps:
      - name: Launch performance regression test
        run: |
          sudo apt install curl
          
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PERF_REG_TOKEN }}"  \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/sofa-framework/PerformanceRegression/dispatches \
          -d '{"event_type":"Launch perf test from SOFA commit","client_payload":{"branch":"master","commit_hash":"${{ github.sha }}"}}'
