name: Post - Release highlight

on:
  release:
    types:
      - created

jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'sofa-framework' }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install pip packages
        run: |
          pip install python-graphql-client
          pip install python-dateutil
          pip install requests
        working-directory: ${{ github.workspace }}

      - name: Run script post-discord-message.py
        run: |
          python scripts/discord/post-discord-message.py
        working-directory: ${{ github.workspace }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_ANNOUNCEMENTS_WEBHOOK_URL }}
          MESSAGE: ":loudspeaker: **New SOFA release** :loudspeaker: \n > SOFA ${{github.event.release.name}} is now available, [check it out](https://github.com/sofa-framework/sofa/releases/tag/${{github.event.release.tag_name}})! \n > For more insights, see the [ChangeLog](https://github.com/sofa-framework/sofa/blob/${{github.event.release.tag_name}}/CHANGELOG.md) \n \n Thanks to all contributors!"
          BOT_NAME: "Release announcement"
          EMBEDS_TITLE: "SOFA ${{github.event.release.name}}"
          EMBEDS_URL: "https://github.com/sofa-framework/sofa/releases/tag/${{github.event.release.tag_name}}"
          EMBEDS_DESCRIPTION: "New source and binary release of SOFA"


